<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

class DbConnection implements \Tyhp\Contracts\IsDisposable
{
    public function dispose(): void
    {
    }
}
