<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App\Lower;

function unaryClone(\App\Lower\Widget $o): \App\Lower\Widget
{
    return clone $o;
}

function parenthesizedUnaryClone(\App\Lower\Widget $o): \App\Lower\Widget
{
    return clone $o;
}

function cloneCallTrailingComma(\App\Lower\Widget $o): \App\Lower\Widget
{
    return clone $o;
}

function cloneCallObjectNamed(\App\Lower\Widget $o): \App\Lower\Widget
{
    return clone $o;
}

function cloneWithLiteral(\App\Lower\Widget $o): \App\Lower\Widget
{
    return \Tyhp\ObjectHelper::with(clone $o, ['x' => 1]);
}

function cloneWithNamed(\App\Lower\Widget $o): \App\Lower\Widget
{
    return \Tyhp\ObjectHelper::with(clone $o, ['x' => 2]);
}

function cloneWithEmpty(\App\Lower\Widget $o): \App\Lower\Widget
{
    return \Tyhp\ObjectHelper::with(clone $o, []);
}

function cloneFcc(): void
{
    $fn = (static fn(object $object, array $withProperties = []) => \Tyhp\ObjectHelper::with(clone $object, $withProperties));
    $fn(new Widget(), ['x' => 3]);
}
