<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App\Lower;

function exitEmpty(): void
{
    exit;
}

function dieEmpty(): void
{
    die;
}

function exitNamed(): void
{
    exit(0);
}

function dieNamed(): void
{
    die(1);
}

function exitFcc(): void
{
    $fn = (static fn(string | int $status = 0) => exit($status));
    $fn(0);
}

function dieFcc(): void
{
    $fn = (static fn(string | int $status = 0) => die($status));
    $fn(1);
}
