<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

const APP_FLAG = 1;

function greet(): string
{
    return 'hi';
}

function demo(): void
{
    $cls = 'User';
    $fn = 'greet';
    $method = 'greet';
    $prop = 'name';
    $case = 'Active';
    $constName = 'APP_FLAG';
    $objConst = 'FLAG';
    $trait = 'HasId';
    $plain = $cls;
    $result = $fn();
}

function takeMethod(string $m): string
{
    return $m;
}

function takeProp(string $p): string
{
    return $p;
}

function takeCase(string $c): string
{
    return $c;
}

function takeConst(string $c): string
{
    return $c;
}

function takeObjConst(string $c): string
{
    return $c;
}

function takeTrait(string $t): string
{
    return $t;
}
