<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

class User
{
    use HasId;

    public const FLAG = 1;
    public string $name;
    public function greet(): string
    {
        return 'hi';
    }
}
