using System.Text.Json.Nodes;
using Microsoft.Extensions.Configuration;
using Tyhp.CLI;
using Tyhp.Config;
using Tyhp.Domain.Enums;
using Tyhp.Domain.Exceptions;
using Tyhp.Domain.Services;

namespace Tyhp.Tests.CLI;

[Trait("Category", "CLI")]
[Collection("ProcessGlobalState")]
public class VendorTyhpdefActionTests : IDisposable
{
    private readonly List<string> _tempDirectories = [];
    private readonly int _previousExitCode = Environment.ExitCode;

    [Fact]
    public void Layout_CompanionNamesAndConstraints()
    {
        VendorTyhpdefLayout.LibraryCompanionName("acme/logger").Should().Be("tyhpdef/acme-logger");
        VendorTyhpdefLayout.PhpExtCompanionName("widgetdb").Should().Be("tyhpdef/php-ext-widgetdb");
        VendorTyhpdefLayout.CompanionConstraintForUpstream("3.10.0").Should().Be("3.10.0.0");
        VendorTyhpdefLayout.CompanionVersionMatchesUpstream("3.10.0.0", "3.10.0").Should().BeTrue();
        VendorTyhpdefLayout.CompanionVersionMatchesUpstream("2.0.0.0", "3.10.0").Should().BeFalse();
        VendorTyhpdefLayout.PackageStubFileName("acme/logger").Should().Be("acme.logger.tyhpdef");
        VendorTyhpdefLayout.ExtensionStubFileName("widget").Should().Be("ExtWidget.tyhpdef");
    }

    [Fact]
    public void Layout_StampInsertsLockedHeader()
    {
        var stamped = VendorTyhpdefLayout.ApplyHeader("<?tyhpdef\nclass Demo {}\n", "acme/widget@1.0.0");
        stamped.Should().Contain("// Generated by `tyhp generate_tyhpdef --vendor`. Do not edit this file.");
        stamped.Should().Contain("not in vendor-tyhpdef/");
        stamped.Should().Contain("// @vendor-identity: acme/widget@1.0.0");
        stamped.Should().StartWith("<?tyhpdef\n");

        var path = Path.Combine(Path.GetTempPath(), "tyhp-vendor-stamp-" + Guid.NewGuid().ToString("N") + ".tyhpdef");
        File.WriteAllText(path, stamped);
        try
        {
            VendorTyhpdefLayout.FileHasMatchingIdentity(path, "acme/widget@1.0.0").Should().BeTrue();
            VendorTyhpdefLayout.FileHasMatchingIdentity(path, "acme/widget@9.9.9").Should().BeFalse();
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void VendorMode_IsExclusiveWithPackagePath()
    {
        var action = RunAction(new Dictionary<string, string?>
        {
            ["vendor"] = "true",
            ["package-path"] = "./vendor/foo/bar",
        });

        action.LastResult!.Success.Should().BeFalse();
        action.LastResult.Diagnostics.Errors.Should().Contain(d =>
            d.Code == MessageCode.TyhpdefGenerationError
            && d.Message.Contains("`--vendor`", StringComparison.Ordinal));
    }

    [Fact]
    public void MissingInstalledJson_Fails()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        var action = RunVendor(
            projectDir,
            new FakeCompanionProbe(),
            new RecordingComposerRunner { ThrowIfCalled = true });

        action.LastResult!.Success.Should().BeFalse();
        action.LastResult.Diagnostics.Errors.Should().Contain(d =>
            d.Code == MessageCode.TyhpdefVendorInstalledJsonMissing);
        action.LastOptions!.Mode.Should().Be(TyhpdefGenerationMode.Vendor);
        action.LastOptions.OutputDirectory.Should().EndWith("vendor-tyhpdef");
    }

    [Fact]
    public void GeneratesIntoVendorTyhpdef_WithHeader_LeavesOverlayUntouched()
    {
        var projectDir = this.CreateProject();
        var overlay = Path.Combine(projectDir, "tyhpdef", "hand.tyhpdef");
        Directory.CreateDirectory(Path.GetDirectoryName(overlay)!);
        const string overlayText = "<?tyhpdef\n// overlay hand file\n";
        File.WriteAllText(overlay, overlayText);

        WriteComposerJson(projectDir, require: new Dictionary<string, string>
        {
            ["php"] = ">=8.2",
            ["acme/widget"] = "^1.0",
        });
        AddInstalledPackage(projectDir, "acme/widget", "1.2.3", php: true);

        var probe = new FakeCompanionProbe();
        var runner = new RecordingComposerRunner();
        var action = RunVendor(projectDir, probe, runner);

        action.LastResult!.Success.Should().BeTrue(
            string.Join("; ", action.LastResult.Diagnostics.Errors.Select(e => e.Message)));
        var stub = Path.Combine(projectDir, "vendor-tyhpdef", "acme.widget.tyhpdef");
        File.Exists(stub).Should().BeTrue();
        var text = File.ReadAllText(stub);
        text.Should().Contain("Generated by `tyhp generate_tyhpdef --vendor`");
        text.Should().Contain("not in vendor-tyhpdef/");
        text.Should().Contain("// @vendor-identity: acme/widget@1.2.3");
        File.Exists(Path.Combine(projectDir, "tyhpdef", "acme.widget.tyhpdef")).Should().BeFalse();
        File.ReadAllText(overlay).Should().Be(overlayText);
        runner.Batches.Should().Contain(b =>
            !b.Dev && b.Packages.Contains("tyhp/core:@dev") && b.Packages.Contains("tyhp/lambda:@dev"));
    }

    [Fact]
    public void SkipTyhpPackageSentinel()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "acme/ready", "2.0.0", php: true, hasTyhpPackage: true);

        var action = RunVendor(projectDir, new FakeCompanionProbe(), new RecordingComposerRunner());

        action.LastResult!.Success.Should().BeTrue();
        File.Exists(Path.Combine(projectDir, "vendor-tyhpdef", "acme.ready.tyhpdef")).Should().BeFalse();
    }

    [Fact]
    public void SkipAlwaysPresentPhpExtensions()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir, require: new Dictionary<string, string>
        {
            ["php"] = ">=8.2",
            ["ext-json"] = "*",
            ["ext-widgetext"] = "*",
        });
        WriteInstalledJson(projectDir, []);

        var runner = new RecordingComposerRunner();
        var action = RunVendor(
            projectDir,
            new FakeCompanionProbe(),
            runner,
            phpExtCatalog: new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "widgetext" });

        action.LastResult!.Success.Should().BeTrue();
        File.Exists(Path.Combine(projectDir, "vendor-tyhpdef", "ExtJson.tyhpdef")).Should().BeFalse();
        runner.Batches.Should().Contain(b =>
            b.Dev && b.Packages.Contains("tyhpdef/php-ext-widgetext:@dev"));
        runner.Batches.Should().NotContain(b =>
            b.Packages.Any(p => p.StartsWith("tyhpdef/php-ext-json", StringComparison.OrdinalIgnoreCase)));
    }

    [Fact]
    public void UnknownExtension_GeneratesExtStub()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir, require: new Dictionary<string, string>
        {
            ["ext-obscurefoo"] = "*",
        });
        WriteInstalledJson(projectDir, []);

        var action = RunVendor(
            projectDir,
            new FakeCompanionProbe(),
            new RecordingComposerRunner(),
            phpExtCatalog: new HashSet<string>(StringComparer.OrdinalIgnoreCase),
            extensionHook: (options, result, _) =>
            {
                Directory.CreateDirectory(options.OutputDirectory);
                var path = options.OutputFileName!;
                File.WriteAllText(path, "<?tyhpdef\nfunction obscurefoo_demo(): void {}\n");
                result.GeneratedFiles.Add(path);
            });

        action.LastResult!.Success.Should().BeTrue(
            string.Join("; ", action.LastResult.Diagnostics.Errors.Select(e => e.Message)));
        var stub = Path.Combine(projectDir, "vendor-tyhpdef", "ExtObscurefoo.tyhpdef");
        File.Exists(stub).Should().BeTrue();
        File.ReadAllText(stub).Should().Contain("Generated by `tyhp generate_tyhpdef --vendor`");
    }

    [Fact]
    public void CompanionProbe_AddsRequireDev_AndDeletesStub()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "acme/logger", "3.10.0", php: true);
        var stubDir = Path.Combine(projectDir, "vendor-tyhpdef");
        Directory.CreateDirectory(stubDir);
        var stub = Path.Combine(stubDir, "acme.logger.tyhpdef");
        File.WriteAllText(stub, "<?tyhpdef\n// stale stub\n");

        var probe = new FakeCompanionProbe
        {
            Available = { ["tyhpdef/acme-logger"] = "3.10.0.0" },
        };
        var runner = new RecordingComposerRunner
        {
            AfterRequire = (dir, args) =>
            {
                if (args.Any(a => a.StartsWith("tyhpdef/acme-logger:", StringComparison.Ordinal)))
                {
                    AddInstalledPackage(dir, "tyhpdef/acme-logger", "3.10.0.0", php: false, hasTyhpPackage: true);
                }
            },
        };

        var action = RunVendor(projectDir, probe, runner);

        action.LastResult!.Success.Should().BeTrue();
        runner.Batches.Should().Contain(b =>
            b.Dev && b.Packages.Contains("tyhpdef/acme-logger:3.10.0"));
        File.Exists(stub).Should().BeFalse();
    }

    [Fact]
    public void BundledPackage_SkipsCommunityCompanionRequire()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "acme/calendar", "3.14.0", php: true, hasTyhpPackage: true);
        var stubDir = Path.Combine(projectDir, "vendor-tyhpdef");
        Directory.CreateDirectory(stubDir);
        var stub = Path.Combine(stubDir, "acme.calendar.tyhpdef");
        var externs = Path.Combine(stubDir, "acme.calendar.externs.tyhpdef");
        File.WriteAllText(stub, "<?tyhpdef\nfunction calendar_stale_stub(): void {}\n");
        File.WriteAllText(externs, "<?tyhpdef\n");
        var probe = new FakeCompanionProbe
        {
            Available = { ["tyhpdef/acme-calendar"] = "3.14.0" },
        };
        var runner = new RecordingComposerRunner();

        var action = RunVendor(projectDir, probe, runner);

        action.LastResult!.Success.Should().BeTrue();
        runner.Batches.Should().NotContain(b =>
            b.Packages.Any(p => p.StartsWith("tyhpdef/acme-calendar", StringComparison.Ordinal)));
        File.Exists(stub).Should().BeFalse();
        File.Exists(externs).Should().BeFalse();
    }

    [Fact]
    public void TyhpdefPointer_RequiresSiblingNotCommunityCompanion()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        var install = AddInstalledPackage(projectDir, "acme/calendar", "3.14.0", php: true);
        File.WriteAllText(Path.Combine(install, "composer.json"), """
            {
                "name": "acme/calendar",
                "version": "3.14.0",
                "autoload": { "psr-4": { "Acme\\": "src/" } },
                "extra": { "tyhp": { "tyhpdef": "acme/calendar-tyhpdef" } }
            }
            """);
        var probe = new FakeCompanionProbe
        {
            Available = { ["tyhpdef/acme-calendar"] = "3.14.0" },
        };
        var runner = new RecordingComposerRunner();

        RunVendor(projectDir, probe, runner);

        runner.Batches.Should().Contain(b =>
            b.Dev && b.Packages.Contains("acme/calendar-tyhpdef:*"));
        runner.Batches.Should().NotContain(b =>
            b.Packages.Any(p => p.StartsWith("tyhpdef/acme-calendar", StringComparison.Ordinal)));
    }

    [Fact]
    public void TyhpdefPointerToImpl_IsNotARootRequire()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        var install = AddInstalledPackage(projectDir, "acme/calendar", "3.14.0", php: true);
        File.WriteAllText(Path.Combine(install, "composer.json"), """
            {
                "name": "acme/calendar",
                "version": "3.14.0",
                "autoload": { "psr-4": { "Acme\\": "src/" } },
                "extra": { "tyhp": { "tyhpdef": "tyhpdef/acme-calendar-impl" } }
            }
            """);
        var probe = new FakeCompanionProbe
        {
            Available =
            {
                ["tyhpdef/acme-calendar"] = "3.14.0",
                ["tyhpdef/acme-calendar-impl"] = "3.14.0.0",
            },
        };
        var runner = new RecordingComposerRunner();

        RunVendor(projectDir, probe, runner);

        runner.Batches.Should().NotContain(b =>
            b.Packages.Any(p => p.Contains("acme-calendar", StringComparison.Ordinal)));
    }

    [Fact]
    public void PublicCompanion_UsesExactUpstreamVersion_NeverRequiresImpl()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "acme/calendar", "3.14.0", php: true);
        AddInstalledPackage(projectDir, "tyhpdef/acme-calendar-impl", "3.14.0.0", php: false, hasTyhpPackage: true);
        var probe = new FakeCompanionProbe
        {
            Available =
            {
                ["tyhpdef/acme-calendar"] = "3.14.0.0",
                ["tyhpdef/acme-calendar-impl"] = "3.14.0.0",
            },
        };
        var runner = new RecordingComposerRunner();

        var action = RunVendor(projectDir, probe, runner);

        action.LastResult!.Success.Should().BeTrue();
        runner.Batches.Should().Contain(b =>
            b.Dev && b.Packages.Contains("tyhpdef/acme-calendar:3.14.0"));
        runner.Batches.Should().NotContain(b =>
            b.Packages.Any(p => p.StartsWith("tyhpdef/acme-calendar-impl", StringComparison.Ordinal)));
    }

    [Fact]
    public void BundledTypesAndImpl_PrefersPhpPackageAndWarns()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "acme/calendar", "3.14.0", php: true, hasTyhpPackage: true);
        AddInstalledPackage(projectDir, "tyhpdef/acme-calendar-impl", "3.14.0.0", php: false, hasTyhpPackage: true);
        var probe = new FakeCompanionProbe
        {
            Available = { ["tyhpdef/acme-calendar"] = "3.14.0" },
        };
        var runner = new RecordingComposerRunner();

        var action = RunVendor(projectDir, probe, runner);

        action.LastResult!.Success.Should().BeTrue();
        action.LastResult.Diagnostics.Warnings.Should().Contain(w =>
            w.Code == MessageCode.TyhpdefBundledPackagePreferred
            && w.FormatParams![0]!.ToString() == "acme/calendar"
            && w.FormatParams[1]!.ToString() == "tyhpdef/acme-calendar-impl");
        runner.Batches.Should().NotContain(b =>
            b.Packages.Any(p => p.Contains("acme-calendar", StringComparison.Ordinal)));
    }

    [Fact]
    public void PublicMetapackageImplPointer_DoesNotRootRequireImpl()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "acme/calendar", "3.14.0", php: true);
        var meta = AddInstalledPackage(projectDir, "tyhpdef/acme-calendar", "3.14.0", php: false, autoload: false);
        File.WriteAllText(Path.Combine(meta, "composer.json"), """
            {
                "name": "tyhpdef/acme-calendar",
                "type": "metapackage",
                "version": "3.14.0",
                "require": { "tyhpdef/acme-calendar-impl": "~3.14.0.0" },
                "extra": { "tyhp": { "impl": "tyhpdef/acme-calendar-impl" } }
            }
            """);
        AddInstalledPackage(projectDir, "tyhpdef/acme-calendar-impl", "3.14.0.0", php: false, hasTyhpPackage: true);
        var runner = new RecordingComposerRunner();

        RunVendor(projectDir, new FakeCompanionProbe(), runner);

        runner.Batches.Should().NotContain(b =>
            b.Packages.Any(p => p.StartsWith("tyhpdef/acme-calendar", StringComparison.Ordinal)));
    }

    [Fact]
    public void RuntimeRequires_AddedAsDevConstraintWhenMissing_DoesNotOverwritePins()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir, require: new Dictionary<string, string>
        {
            ["php"] = ">=8.2",
            ["tyhpdef/php"] = "^805.0",
        });
        WriteInstalledJson(projectDir, []);

        var runner = new RecordingComposerRunner();
        RunVendor(projectDir, new FakeCompanionProbe(), runner);

        var requireBatch = runner.Batches.Single(b => !b.Dev);
        requireBatch.Packages.Should().Contain("tyhp/core:@dev");
        requireBatch.Packages.Should().Contain("tyhp/async:@dev");
        requireBatch.Packages.Should().Contain("tyhp/lambda:@dev");
        requireBatch.Packages.Should().Contain("tyhp/decimal:@dev");
        requireBatch.Packages.Should().NotContain(p => p.StartsWith("tyhpdef/php:", StringComparison.Ordinal));
        runner.Batches.Should().NotContain(b =>
            b.Dev && b.Packages.Any(p => p.StartsWith("tyhpdef/php:", StringComparison.Ordinal)));
        runner.Batches.Should().OnlyContain(b => b.NoScripts);
    }

    [Fact]
    public void TyhpdefPhp_AddedToRequireDevWhenMissing()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir, require: new Dictionary<string, string>
        {
            ["php"] = ">=8.2",
        });
        WriteInstalledJson(projectDir, []);

        var runner = new RecordingComposerRunner();
        RunVendor(projectDir, new FakeCompanionProbe(), runner);

        runner.Batches.Should().Contain(b =>
            b.Dev && b.Packages.Contains("tyhpdef/php:@dev"));
        runner.Batches.Should().NotContain(b =>
            !b.Dev && b.Packages.Any(p => p.StartsWith("tyhpdef/php:", StringComparison.Ordinal)));
    }

    [Fact]
    public void SkipCompilerAndEmptyPackages()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "tyhp/compiler", "1.0.0", php: true);
        AddInstalledPackage(projectDir, "acme/meta", "1.0.0", php: false, autoload: false);

        var action = RunVendor(projectDir, new FakeCompanionProbe(), new RecordingComposerRunner());

        action.LastResult!.Success.Should().BeTrue();
        Directory.Exists(Path.Combine(projectDir, "vendor-tyhpdef")).Should().BeTrue();
        File.Exists(Path.Combine(projectDir, "vendor-tyhpdef", "tyhp.compiler.tyhpdef")).Should().BeFalse();
        File.Exists(Path.Combine(projectDir, "vendor-tyhpdef", "acme.meta.tyhpdef")).Should().BeFalse();
    }

    [Fact]
    public void IdentityStamp_SkipsWithoutOverwrite()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "acme/widget", "1.0.0", php: true);

        RunVendor(projectDir, new FakeCompanionProbe(), new RecordingComposerRunner());
        var stub = Path.Combine(projectDir, "vendor-tyhpdef", "acme.widget.tyhpdef");
        File.AppendAllText(stub, "// marker\n");

        RunVendor(projectDir, new FakeCompanionProbe(), new RecordingComposerRunner());
        File.ReadAllText(stub).Should().Contain("// marker");

        RunVendor(projectDir, new FakeCompanionProbe(), new RecordingComposerRunner(), overwrite: true);
        File.ReadAllText(stub).Should().NotContain("// marker");
    }

    [Fact]
    public void ReentryEnv_SkipsVendorGenerate()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "acme/widget", "1.0.0", php: true);

        var env = new Dictionary<string, string?>(StringComparer.Ordinal)
        {
            [VendorTyhpdefLayout.VendorRunningEnvironmentVariable] = "1",
        };
        var action = RunVendor(
            projectDir,
            new FakeCompanionProbe(),
            new RecordingComposerRunner { ThrowIfCalled = true },
            readEnv: key => env.GetValueOrDefault(key));

        action.LastResult!.Success.Should().BeTrue();
        File.Exists(Path.Combine(projectDir, "vendor-tyhpdef", "acme.widget.tyhpdef")).Should().BeFalse();
    }

    [Fact]
    public void NoVendorEnv_DirectInvocationStillRuns()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "acme/widget", "1.0.0", php: true);

        var env = new Dictionary<string, string?>(StringComparer.Ordinal)
        {
            [VendorTyhpdefLayout.NoVendorEnvironmentVariable] = "1",
        };
        var action = RunVendor(
            projectDir,
            new FakeCompanionProbe(),
            new RecordingComposerRunner(),
            readEnv: key => env.GetValueOrDefault(key));

        action.LastResult!.Success.Should().BeTrue();
        File.Exists(Path.Combine(projectDir, "vendor-tyhpdef", "acme.widget.tyhpdef")).Should().BeTrue();
    }

    [Fact]
    public void ComposerAction_NoTyhpdef_SkipsHook()
    {
        var projectDir = this.CreateProject();
        var action = CreateComposerAction(
            projectDir,
            ["install"],
            noTyhpdef: true,
            vendorGenerator: new VendorTyhpdefGenerator
            {
                ComposerRunner = new RecordingComposerRunner { ThrowIfCalled = true },
                ReadEnvironment = _ => null,
            });

        action.Start(CancellationToken.None);

        Environment.ExitCode.Should().Be((int)ExitCode.Success);
        action.LastVendorResult.Should().BeNull();
    }

    [Fact]
    public void ComposerAction_Install_RunsVendorHook()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "acme/widget", "1.0.0", php: true);

        var action = CreateComposerAction(
            projectDir,
            ["install"],
            vendorGenerator: new VendorTyhpdefGenerator
            {
                CompanionProbe = new FakeCompanionProbe(),
                ComposerRunner = new RecordingComposerRunner(),
                FirstPartyPhpExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase),
                ReadEnvironment = _ => null,
            });

        action.Start(CancellationToken.None);

        Environment.ExitCode.Should().Be((int)ExitCode.Success);
        action.LastVendorResult.Should().NotBeNull();
        action.LastVendorResult!.Success.Should().BeTrue();
        File.Exists(Path.Combine(projectDir, "vendor-tyhpdef", "acme.widget.tyhpdef")).Should().BeTrue();
    }

    [Fact]
    public void ComposerAction_NoVendorEnv_SkipsHook()
    {
        var projectDir = this.CreateProject();
        WriteComposerJson(projectDir);
        AddInstalledPackage(projectDir, "acme/widget", "1.0.0", php: true);

        var action = CreateComposerAction(
            projectDir,
            ["update"],
            vendorGenerator: new VendorTyhpdefGenerator
            {
                ComposerRunner = new RecordingComposerRunner { ThrowIfCalled = true },
            },
            readEnv: key => key == VendorTyhpdefLayout.NoVendorEnvironmentVariable ? "1" : null);

        action.Start(CancellationToken.None);

        Environment.ExitCode.Should().Be((int)ExitCode.Success);
        action.LastVendorResult.Should().BeNull();
        File.Exists(Path.Combine(projectDir, "vendor-tyhpdef", "acme.widget.tyhpdef")).Should().BeFalse();
    }

    [Fact]
    public void Probe_PrefersPathRepositoryOverPackagist()
    {
        var projectDir = this.CreateProject();
        var companionDir = Path.Combine(projectDir, "companions", "tyhp-acme-widget");
        Directory.CreateDirectory(companionDir);
        File.WriteAllText(
            Path.Combine(companionDir, "composer.json"),
            """{"name":"tyhpdef/acme-widget","version":"1.2.3.0"}""");
        WriteComposerJson(
            projectDir,
            repositories:
            [
                """{"type":"path","url":"./companions/tyhp-acme-widget"}""",
            ]);

        var httpCalls = new List<Uri>();
        var probe = new CompanionPackageProbe
        {
            Fetch = uri =>
            {
                httpCalls.Add(uri);
                return null;
            },
        };

        probe.TryResolve("tyhpdef/acme-widget", "1.2.3", projectDir, out var constraint).Should().BeTrue();
        constraint.Should().Be("1.2.3.0");
        httpCalls.Should().BeEmpty();
    }

    [Fact]
    public void ExpandBareBooleanFlags_VendorBareBecomesTrue()
    {
        ActionConfigProvider.ExpandBareBooleanFlags(["generate_tyhpdef", "--vendor"])
            .Should().Equal("generate_tyhpdef", "--vendor=true");
        ActionConfigProvider.ExpandBareBooleanFlags(["generate_tyhpdef", "--vendor=/tmp/vendor"])
            .Should().Equal("generate_tyhpdef", "--vendor=/tmp/vendor");
        ActionConfigProvider.BareBooleanFlags.Should().Contain("--vendor");
    }

    private GenerateTyhpdefAction RunVendor(
        string projectDir,
        ICompanionPackageProbe probe,
        IComposerCommandRunner runner,
        IReadOnlySet<string>? phpExtCatalog = null,
        Action<TyhpdefGenerationOptions, TyhpdefGenerationResult, CancellationToken>? extensionHook = null,
        Func<string, string?>? readEnv = null,
        bool overwrite = false)
    {
        var settings = new Dictionary<string, string?>
        {
            ["*project_file_path"] = Path.Combine(projectDir, "tyhp.json"),
            ["vendor"] = "true",
            ["quiet"] = "true",
            ["overwrite"] = overwrite ? "true" : "false",
            ["no-docs"] = "true",
        };
        var project = new Project(new ConfigurationBuilder().AddInMemoryCollection(settings).Build());
        Environment.ExitCode = (int)ExitCode.Success;
        var action = new GenerateTyhpdefAction(project)
        {
            VendorGenerator = new VendorTyhpdefGenerator
            {
                CompanionProbe = probe,
                ComposerRunner = runner,
                FirstPartyPhpExtensions = phpExtCatalog ?? new HashSet<string>(StringComparer.OrdinalIgnoreCase),
                ExtensionGenerateHook = extensionHook,
                ReadEnvironment = readEnv ?? (_ => null),
                AlwaysPresentExtensions = _ => VendorTyhpdefLayout.AlwaysPresentPhpExtensions,
            },
        };
        action.Start(CancellationToken.None);
        return action;
    }

    private ComposerAction CreateComposerAction(
        string projectDir,
        string[] composerArgs,
        VendorTyhpdefGenerator? vendorGenerator = null,
        bool noTyhpdef = false,
        Func<string, string?>? readEnv = null)
    {
        var settings = new Dictionary<string, string?>
        {
            ["*project_file_path"] = Path.Combine(projectDir, "tyhp.json"),
            ["quiet"] = "true",
            ["no-tyhpdef"] = noTyhpdef ? "true" : "false",
        };
        var project = new Project(new ConfigurationBuilder().AddInMemoryCollection(settings).Build());
        Environment.ExitCode = (int)ExitCode.Success;
        return new ComposerAction(project)
        {
            Args = composerArgs,
            FindPhp = () => "/usr/bin/php",
            ResolveComposer = _ => "/usr/bin/composer",
            RunComposerProcess = (_, _, _) => 0,
            VendorGenerator = vendorGenerator,
            ReadEnvironment = readEnv ?? (_ => null),
        };
    }

    private static GenerateTyhpdefAction RunAction(Dictionary<string, string?> settings)
    {
        var values = new Dictionary<string, string?>(settings) { ["quiet"] = "true" };
        var project = new Project(new ConfigurationBuilder().AddInMemoryCollection(values).Build());
        Environment.ExitCode = (int)ExitCode.Success;
        var action = new GenerateTyhpdefAction(project);
        action.Start(CancellationToken.None);
        return action;
    }

    private string CreateProject()
    {
        var dir = Path.Combine(Path.GetTempPath(), "tyhp-vendor-test", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        Directory.CreateDirectory(Path.Combine(dir, "vendor", "composer"));
        File.WriteAllText(Path.Combine(dir, "tyhp.json"), """{"include":["src/**/*.tyhp"]}""");
        this._tempDirectories.Add(dir);
        return dir;
    }

    private static void WriteComposerJson(
        string projectDir,
        Dictionary<string, string>? require = null,
        Dictionary<string, string>? requireDev = null,
        IReadOnlyList<string>? repositories = null)
    {
        require ??= new Dictionary<string, string> { ["php"] = ">=8.2" };
        var requireJson = string.Join(",", require.Select(kv => $"\"{kv.Key}\": \"{kv.Value}\""));
        var requireDevJson = requireDev is { Count: > 0 }
            ? ",\"require-dev\": {" + string.Join(",", requireDev.Select(kv => $"\"{kv.Key}\": \"{kv.Value}\"")) + "}"
            : "";
        var reposJson = repositories is { Count: > 0 }
            ? ",\"repositories\": [" + string.Join(",", repositories) + "]"
            : "";
        File.WriteAllText(
            Path.Combine(projectDir, "composer.json"),
            "{\"name\":\"app/tyhp-project\",\"require\":{" + requireJson + "}" + requireDevJson + reposJson + "}");
    }

    private static void WriteInstalledJson(string projectDir, IReadOnlyList<string> packageJsonObjects)
    {
        var path = Path.Combine(projectDir, "vendor", "composer", "installed.json");
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, "{\"packages\":[" + string.Join(",", packageJsonObjects) + "],\"dev\":true}");
    }

    private static string AddInstalledPackage(
        string projectDir,
        string name,
        string version,
        bool php,
        bool autoload = true,
        bool hasTyhpPackage = false)
    {
        var slash = name.IndexOf('/');
        var vendor = name[..slash];
        var pkg = name[(slash + 1)..];
        var install = Path.Combine(projectDir, "vendor", vendor, pkg);
        Directory.CreateDirectory(install);
        var autoloadJson = autoload
            ? """{"psr-4":{"Acme\\":"src/"}}"""
            : "{}";
        File.WriteAllText(
            Path.Combine(install, "composer.json"),
            "{\"name\":\"" + name + "\",\"version\":\"" + version + "\",\"autoload\":" + autoloadJson
            + (hasTyhpPackage
                ? ",\"extra\":{\"tyhp\":{\"package\":{}}}"
                : "")
            + "}");
        if (php)
        {
            var src = Path.Combine(install, "src");
            Directory.CreateDirectory(src);
            File.WriteAllText(src + "/Widget.php", "<?php\nnamespace Acme;\nclass Widget { public function ping(): int { return 1; } }\n");
        }

        var relativeInstall = "../" + vendor + "/" + pkg;
        var existingPath = Path.Combine(projectDir, "vendor", "composer", "installed.json");
        var packages = new JsonArray();
        if (File.Exists(existingPath))
        {
            try
            {
                var root = JsonNode.Parse(File.ReadAllText(existingPath))?.AsObject();
                if (root?["packages"] is JsonArray existing)
                {
                    foreach (var item in existing)
                    {
                        if (item is not null)
                        {
                            packages.Add(item.DeepClone());
                        }
                    }
                }
            }
            catch (Exception)
            {
            }
        }

        packages.Add(new JsonObject
        {
            ["name"] = name,
            ["version"] = version,
            ["type"] = "library",
            ["install-path"] = relativeInstall,
        });
        var installed = new JsonObject
        {
            ["packages"] = packages,
            ["dev"] = true,
        };
        File.WriteAllText(existingPath, installed.ToJsonString() + Environment.NewLine);
        return install;
    }

    public void Dispose()
    {
        Environment.ExitCode = this._previousExitCode;
        foreach (var directory in this._tempDirectories)
        {
            try
            {
                if (Directory.Exists(directory))
                {
                    Directory.Delete(directory, recursive: true);
                }
            }
            catch (IOException)
            {
            }
        }
    }

    private sealed class FakeCompanionProbe : ICompanionPackageProbe
    {
        public Dictionary<string, string> Available { get; } = new(StringComparer.OrdinalIgnoreCase);

        public int FetchCount { get; private set; }

        public bool TryResolve(string companionPackageName, string? upstreamVersion, string projectRoot, out string constraint)
        {
            this.FetchCount++;
            if (this.Available.TryGetValue(companionPackageName, out constraint!))
            {
                return true;
            }

            constraint = "";
            return false;
        }
    }

    private sealed class RecordingComposerRunner : IComposerCommandRunner
    {
        public List<(bool Dev, bool NoScripts, List<string> Packages)> Batches { get; } = [];

        public bool ThrowIfCalled { get; init; }

        public Action<string, IReadOnlyList<string>>? AfterRequire { get; init; }

        public ComposerCommandResult Run(
            string projectRoot,
            IReadOnlyList<string> arguments,
            IReadOnlyDictionary<string, string>? extraEnvironment)
        {
            if (this.ThrowIfCalled)
            {
                throw new InvalidOperationException("Composer must not run");
            }

            extraEnvironment.Should().NotBeNull();
            extraEnvironment!.Should().ContainKey(VendorTyhpdefLayout.VendorRunningEnvironmentVariable);
            var dev = arguments.Contains("--dev");
            var noScripts = arguments.Contains("--no-scripts");
            var packages = arguments.Where(a => a.Contains(':', StringComparison.Ordinal) && !a.StartsWith("--")).ToList();
            this.Batches.Add((dev, noScripts, packages));
            this.AfterRequire?.Invoke(projectRoot, arguments);
            return new ComposerCommandResult(0, "", "");
        }
    }
}
