<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App\Lower;

#[\Attribute]
class ConstMarker
{
    public function __construct(public string $label = '')
    {
    }
}
