<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function takeStructKey(string $k): string
{
    return $k;
}

function takeProps(array $p): array
{
    return $p;
}

function takeReturn(int $r): int
{
    return $r;
}

function takeParams(array $p): array
{
    return $p;
}

function takeStructDef(array $s): array
{
    return $s;
}

function demo(): void
{
    $key = '$x';
    $props = ['x' => 1];
    $ret = 1;
    $plain = $key;
    takeStructKey('$x');
    takeProps(['x' => 1]);
    takeProps([]);
    takeReturn(1);
}
