<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function fetchRaw(int $id): \Tyhp\Promise
{
    return \Tyhp\Promise::_async(function () use ($id): string {
        return "id-" . $id;
    });
}

function fetchData(int $id): \Tyhp\Promise
{
    return \Tyhp\Promise::_async(function () use ($id): string {
        return \Tyhp\Promise::_await(fetchRaw($id));
    });
}
