<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App\Types;

function UserId(): \Tyhp\Type
{
    return \Tyhp\Type::int();
}

function Optional(?\Tyhp\Type $T = null): \Tyhp\Type
{
    $T ??= \Tyhp\Type::mixed();
    return \Tyhp\Type::nullable($T);
}
