<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function unaryClone(\App\Widget $o): \App\Widget
{
    return clone $o;
}

function parenthesizedUnaryClone(\App\Widget $o): \App\Widget
{
    return clone $o;
}

function cloneCallTrailingComma(\App\Widget $o): \App\Widget
{
    return clone($o);
}

function cloneCallObjectNamed(\App\Widget $o): \App\Widget
{
    return clone(object: $o);
}

function cloneWithLiteral(\App\Widget $o): \App\Widget
{
    return clone($o, ['x' => 1]);
}

function cloneWithNamed(\App\Widget $o): \App\Widget
{
    return clone(object: $o, withProperties: ['x' => 2]);
}

function cloneWithEmpty(\App\Widget $o): \App\Widget
{
    return clone($o, []);
}

function cloneFcc(): void
{
    $fn = clone(...);
    $fn(new Widget(), ['x' => 3]);
}
