#!/usr/bin/env python3
"""Emit tyhpdef grammar-method partials and visitor includes.

PHP grammar-method files and Visitor/shared/*.cs are the source.
This script writes the renamed tyhpdef copies and the visitor partials.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PARSER = ROOT / "Tyhp/TyhpLang/Parser"
VISITOR = ROOT / "Tyhp/TyhpLang/Visitor"
SHARED = VISITOR / "shared"

GENERATED = (
    "// Generated by compile_grammar_emit_partials.py. Do not edit.\n"
    "// Source: Tyhp/TyhpLang/Visitor/shared/. Re-run ./compile_grammar.sh to regenerate.\n"
)


def replace_tyhpdef_types(text: str) -> str:
    text = text.replace("TyhpParserAstVisitor", "\0TYHP_VISITOR\0")
    text = text.replace("TyhpParser", "TyhpdefParser")
    text = text.replace("TyhpLexer", "TyhpdefLexer")
    text = text.replace("\0TYHP_VISITOR\0", "TyhpParserAstVisitor")
    text = text.replace(
        "PhpParserAstVisitor.GetCurrentLanguageMode",
        "TyhpdefIncludedPhpVisits.GetCurrentLanguageMode",
    )
    return text


def emit_grammar_methods() -> None:
    pairs = [
        ("TyhpLexer.GrammarMethods.cs", "TyhpdefLexer.GrammarMethods.cs"),
        ("TyhpParser.GrammarMethods.cs", "TyhpdefParser.GrammarMethods.cs"),
    ]
    for src_name, dst_name in pairs:
        text = (PARSER / src_name).read_text(encoding="utf-8")
        (PARSER / dst_name).write_text(replace_tyhpdef_types(text), encoding="utf-8")
        print(f"emitted {dst_name}")


def wrap_partial(class_name: str, bases: str, usings: list[str], body: str) -> str:
    using_block = "".join(f"    using {u};\n" for u in usings)
    base_clause = f" : {bases}" if bases else ""
    return (
        GENERATED
        + "namespace Tyhp.TyhpLang.Visitor\n"
        + "{\n"
        + using_block
        + f"    public partial class {class_name}{base_clause}\n"
        + "    {\n"
        + body
        + "    }\n"
        + "}\n"
    )


def emit_visitors() -> None:
    if not SHARED.is_dir():
        print("no visitor shared directory; skip visitor emit")
        return
    groups: dict[str, list[str]] = {
        "PhpParserAstVisitor": [],
        "TyhpParserAstVisitor": [],
    }
    usings: dict[str, list[str]] = {k: [] for k in groups}
    for path in sorted(SHARED.rglob("*.inc")):
        text = path.read_text(encoding="utf-8")
        match = re.search(r"(?m)^// #class (\w+)\s*$", text)
        if not match:
            raise SystemExit(f"{path} missing // #class")
        owner = match.group(1)
        if owner not in groups:
            raise SystemExit(f"{path} unknown class {owner}")
        file_usings = re.findall(r"(?m)^// #using (.+)$", text)
        for item in file_usings:
            if item not in usings[owner]:
                usings[owner].append(item)
        body = re.sub(r"(?m)^// #(class|using) .*\n", "", text)
        groups[owner].append(body if body.endswith("\n") else body + "\n")

    php_body = "".join(groups["PhpParserAstVisitor"])
    tyhp_body = "".join(groups["TyhpParserAstVisitor"])
    (VISITOR / "PhpParserAstVisitor.Included.cs").write_text(
        wrap_partial("PhpParserAstVisitor", "", usings["PhpParserAstVisitor"], php_body),
        encoding="utf-8",
    )
    (VISITOR / "TyhpParserAstVisitor.Included.cs").write_text(
        wrap_partial("TyhpParserAstVisitor", "", usings["TyhpParserAstVisitor"], tyhp_body),
        encoding="utf-8",
    )
    php_usings = usings["PhpParserAstVisitor"]
    tyhp_usings = list(usings["TyhpParserAstVisitor"])
    for item in php_usings:
        if item not in tyhp_usings:
            tyhp_usings.append(item)
    (VISITOR / "TyhpdefIncludedPhpVisits.Included.cs").write_text(
        wrap_partial(
            "TyhpdefIncludedPhpVisits",
            "",
            php_usings,
            replace_tyhpdef_types(php_body),
        ),
        encoding="utf-8",
    )
    (VISITOR / "TyhpdefParserAstVisitor.Included.cs").write_text(
        wrap_partial(
            "TyhpdefParserAstVisitor",
            "",
            tyhp_usings,
            replace_tyhpdef_types(tyhp_body),
        ),
        encoding="utf-8",
    )
    print("emitted visitor includes")


def main() -> None:
    emit_grammar_methods()
    emit_visitors()


if __name__ == "__main__":
    main()
