<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function always_present(): void {}

function from_83(): void {}

function from_84(): void {}

function block_84(): void {}

function example(string $v, bool $strict = false): string
{
    return $v;
}
