<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

class GatedStringOps
{
    public static function gated_tag(string $this_): string
    {
        return \strtoupper($this_);
    }
}
