<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function add(\App\Money $a, \App\Money $b): \App\Money
{
    return \App\Money::__add($a, $b);
}

function demo(): void
{
    $a = new Money(100, "USD");
    $b = new Money(50, "USD");
    $c = add($a, $b);
}
