<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

class Money
{
    public function __construct(public readonly int $amount, public readonly string $currency)
    {
    }
    public static function __add(self $l, self $r): static
    {
        if ($l instanceof self && $r instanceof self) {
            $left = $l;
            $right = $r;
            return new self($left->amount + $right->amount, $left->currency);
        } else {
            throw new \Tyhp\Exceptions\InvalidParametersForOperatorOverloadException(static::class, __FUNCTION__, $l, $r);
        }
    }
}
