<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function demo(): void
{
    $__scope_0 = \Tyhp\DisposableScope::create();
    $h = $__scope_0->using(new Handle());
}
