<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

class Container
{
    use \Tyhp\Concerns\HasGenerics;

    private static ?\ReflectionClass $__reflectedClass__tyhpGeneric = null;
    private mixed $item = null {
        set(mixed $value) {
            $this->__tyhpGeneric->checkProperty('item', $value);
            $this->item = $value;
        }
    }
    public function __construct()
    {
        $this->tyhpBootTraits();
        if ($this->__tyhpGeneric->needsInit()) {
            self::__initGenerics__tyhpGeneric(null);
        }
        $this->__tyhpGeneric->enablePropertyChecks();
    }
    final public static function new_App_Container__tyhpGeneric(?\Tyhp\Type $__generic_TValue): self
    {
        self::$__reflectedClass__tyhpGeneric ??= new \ReflectionClass(self::class);
        $__tyhp_obj = self::$__reflectedClass__tyhpGeneric->newInstanceWithoutConstructor();
        $__tyhp_obj->__initGenerics__tyhpGeneric($__generic_TValue);
        $__tyhp_obj->__construct();
        return $__tyhp_obj;
    }
    public function set(mixed $value): void
    {
        $this->item = $value;
    }
    public function get(): mixed
    {
        return $this->item;
    }
    protected function __initGenerics__tyhpGeneric(?\Tyhp\Type ...$generics): void
    {
        $this->tyhpBootTraits();
        if ($this->__tyhpGeneric->isInitialized(\App\Container::class)) {
            return;
        }
        $tValue = $generics[0] ?? \Tyhp\Type::mixed();
        $this->__tyhpGeneric->init(static::class, \App\Container::class, new \Tyhp\NamedType('TValue', $tValue));
        $this->__tyhpGeneric->setPropertyType('item', \Tyhp\Type::nullable($tValue));
        $this->__tyhpGeneric->markBound();
    }
}
