<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

class UserService
{
    public static function NameType(): \Tyhp\Type
    {
        return \Tyhp\Type::string();
    }
}
