using System.Net;
using System.Text;

namespace Tyhp.Domain.Diagnostics
{
    /// <summary>
    /// Generates the docs-site diagnostic code index from <see cref="MessageCodeCatalog"/>
    /// so <c>docs/content/diagnostics_reference.md</c> stays in sync with
    /// <c>MessageCode.cs</c> and the <c>.resx</c> short-message catalog.
    /// </summary>
    public static class DiagnosticsReferenceGenerator
    {
        public const string GeneratedMarker =
            "<!-- GENERATED by Tyhp.Domain.Diagnostics.DiagnosticsReferenceGenerator — do not edit message entries by hand. Regenerate: TYHP_UPDATE_DIAGNOSTICS_REFERENCE=1 dotnet test --filter DiagnosticsReferenceGeneratorTests -->";

        /// <summary>
        /// Builds the full markdown page for the diagnostic code reference.
        /// </summary>
        /// <remarks>
        /// Lines are terminated with <c>\n</c> rather than <see cref="Environment.NewLine"/> so the
        /// committed page and the drift check agree regardless of the host operating system.
        /// </remarks>
        public static string GenerateMarkdown()
        {
            var sb = new StringBuilder();
            void Line(string text = "") => sb.Append(text).Append('\n');

            Line("---");
            Line("title: 'Diagnostic Code Reference'");
            Line("status:");
            Line("  tier: 1");
            Line("  story: '14'");
            Line("  state: complete");
            Line("---");
            Line();
            Line(GeneratedMarker);
            Line();
            Line("This page is the comprehensive index of Tyhp compiler diagnostic codes. Every entry is");
            Line("generated from the compiler's code registry (`MessageCode.cs`) and the localized short-message");
            Line("catalog (`.resx`), so the message text always matches what the compiler emits.");
            Line();
            Line(":::note");
            Line("Diagnostic codes are stable identifiers. Once assigned, a code number always refers to the same");
            Line("diagnostic, even across compiler versions. The canonical list of codes lives in");
            Line("`Tyhp/Domain/Exceptions/MessageCode.cs`.");
            Line(":::");
            Line();
            Line(":::tip");
            Line("Run <code>tyhp --explain TYHP####</code> (or <code>tyhp explain ####</code>) to print the");
            Line("long-form explanation for any code. That command reads the same dynamic catalog as this page.");
            Line(":::");
            Line();
            Line("## Looking up a code");
            Line();
            Line("```bash");
            Line("tyhp --explain TYHP4008");
            Line("tyhp explain 4008");
            Line("tyhp explain --code=TYHP3003");
            Line("```");

            MessageCodeCategory? current = null;
            foreach (var entry in MessageCodeCatalog.All)
            {
                if (current != entry.Category)
                {
                    current = entry.Category;
                    Line();
                    Line("## " + CategoryHeading(entry.Category));
                    Line();
                    Line(CategoryIntro(entry.Category));
                    Line();
                }

                var codeId = MessageCodeCatalog.FormatCode(entry.Code);
                var severityLabel = string.Join(
                    ", ",
                    entry.Variants.Select(v => SeverityLabel(v.Severity)));

                Line($":::member[{codeId} ({severityLabel})]");
                Line($"**{entry.Name}.** " + FormatMessages(entry));

                if (MessageCodeCatalog.TryGetAuthoredLongForm(entry, out var longForm))
                {
                    foreach (var block in MessageCodeCatalog.SplitLongFormBlocks(longForm))
                    {
                        Line();
                        if (block.IsCodeFence)
                        {
                            foreach (var fenceLine in block.Text.Split('\n'))
                            {
                                Line(fenceLine);
                            }
                        }
                        else
                        {
                            Line(block.Text);
                        }
                    }
                }
                else
                {
                    Line($"Run <code>tyhp --explain {codeId}</code> for the long-form explanation.");
                }

                Line(":::");
                Line();
            }

            return sb.ToString();
        }

        /// <summary>
        /// Renders the catalog text for a code, labeling each severity only when a code carries
        /// different wording per severity.
        /// </summary>
        private static string FormatMessages(MessageCodeEntry entry)
        {
            var distinct = entry.Variants
                .Select(v => v.ShortMessage)
                .Distinct(StringComparer.Ordinal)
                .ToList();

            if (distinct.Count == 1)
            {
                return $"Message: <code>{WebUtility.HtmlEncode(distinct[0])}</code>.";
            }

            var parts = entry.Variants.Select(
                v => $"{SeverityLabel(v.Severity)} — <code>{WebUtility.HtmlEncode(v.ShortMessage)}</code>");
            return "Messages: " + string.Join("; ", parts) + ".";
        }

        private static string SeverityLabel(DiagnosticSeverity severity)
            => severity switch
            {
                DiagnosticSeverity.Warning => "Warning",
                DiagnosticSeverity.Info => "Info",
                DiagnosticSeverity.Hint => "Hint",
                _ => "Error",
            };

        private static string CategoryHeading(MessageCodeCategory category)
            => category switch
            {
                MessageCodeCategory.Parser => "Parser Errors (TYHP1xxx)",
                MessageCodeCategory.Visitor => "Visitor Errors (TYHP2xxx)",
                MessageCodeCategory.Binder => "Binder Errors (TYHP3xxx)",
                MessageCodeCategory.Checker => "Checker Errors (TYHP4xxx)",
                MessageCodeCategory.Emitter => "Emitter Errors (TYHP5xxx)",
                MessageCodeCategory.Configuration => "Configuration Errors (TYHP6xxx)",
                MessageCodeCategory.Cli => "CLI Errors (TYHP7xxx)",
                MessageCodeCategory.Tyhpdef => "Tyhpdef Errors (TYHP8xxx)",
                MessageCodeCategory.Internal => "Internal Errors (TYHP9xxx)",
                _ => "Other Diagnostics",
            };

        private static string CategoryIntro(MessageCodeCategory category)
            => category switch
            {
                MessageCodeCategory.Parser =>
                    "Parser errors occur during the ANTLR4 lexing and parsing phase when the compiler encounters syntax it cannot understand.",
                MessageCodeCategory.Visitor =>
                    "Visitor errors occur during parse-tree to AST conversion when the visitor encounters an unexpected structure or unsupported construct.",
                MessageCodeCategory.Binder =>
                    "Binder errors occur during symbol resolution and scope management.",
                MessageCodeCategory.Checker =>
                    "Checker errors occur during type checking and semantic analysis.",
                MessageCodeCategory.Emitter =>
                    "Emitter errors occur during PHP code generation.",
                MessageCodeCategory.Configuration =>
                    "Configuration errors are reported when `tyhp.json` or CLI options are invalid.",
                MessageCodeCategory.Cli =>
                    "CLI errors are reported by compiler actions (build, lint, init, and related commands).",
                MessageCodeCategory.Tyhpdef =>
                    "Tyhpdef errors are reported when loading or validating type-definition files.",
                MessageCodeCategory.Internal =>
                    "Internal compiler errors indicate unexpected failures inside the compiler itself.",
                _ =>
                    "Additional diagnostic codes outside the primary component bands.",
            };
    }
}
