<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

interface HasTitle
{
    public string $title {
        #[\App\HookMarker] get;
        #[\App\HookMarker] set;
    }
}
