<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

final class Widget
{
    public string $name {
        #[\App\HookMarker] get {
            return $this->name;
        }
        #[\App\HookMarker] set {
            $this->name = $value;
        }
    }
}
