<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App\Lower;

function discardable(int $n): int
{
    return $n;
}

function side(): int
{
    return 1;
}

function voidCastVariable(int $n): void
{
    $n;
}

function voidCastCall(int $n): void
{
    discardable($n);
}

function voidCastForLists(): void
{
    $a = 0;
    $i = 0;
    for ($a; $i < 10; $i++) {
    }
}

function voidCastForCond(bool $cond): void
{
    for (; side(), $cond; ) {
    }
}
