<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace Demo;

use App\UserService;

use function App\Types\Optional;
use function App\Types\UserId;

function demo(mixed $x): mixed
{
    UserId();
    UserId();
    Optional(\Tyhp\Type::int());
    Optional(\Tyhp\Type::int());
    \Tyhp\Type::is($x, UserId());
    UserId()->defaultValue();
    return \App\UserService::NameType();
}
