<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace MixedNs;

use App\Types\User;

use function App\Types\UserId;

function take(int $id): \App\Types\User
{
    UserId();
    return new \App\Types\User();
}
