<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function sortBy(\Tyhp\Expression $cmp): void
{
}

function take(\Tyhp\Expression $pred): void
{
}

function demo(): void
{
    sortBy(new \Tyhp\Expression(body: new \Tyhp\Expression\BinaryExpression(new \Tyhp\Expression\PropertyAccessExpression(new \Tyhp\Expression\ParameterExpression('a', \App\User::class, 0), 'lastName', 'string'), '<=>', new \Tyhp\Expression\PropertyAccessExpression(new \Tyhp\Expression\ParameterExpression('b', \App\User::class, 1), 'lastName', 'string'), 'int'), parameters: [new \Tyhp\Expression\ParameterExpression('a', \App\User::class, 0), new \Tyhp\Expression\ParameterExpression('b', \App\User::class, 1)], callable: fn(\App\User $a, \App\User $b): int => $a->lastName <=> $b->lastName, returnType: 'int'));
    take(new \Tyhp\Expression(body: new \Tyhp\Expression\InstanceofExpression(new \Tyhp\Expression\PropertyAccessExpression(new \Tyhp\Expression\ParameterExpression('u', \App\User::class, 0), 'value', 'mixed'), 'int', 'bool'), parameters: [new \Tyhp\Expression\ParameterExpression('u', \App\User::class, 0)], callable: fn(\App\User $u): bool => \Tyhp\Type::is($u->value, \Tyhp\Type::int()), returnType: 'bool'));
    $col = 'lastName';
}
