<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

class StringExtensions
{
    public static function shout(string $this_): string
    {
        return \strtoupper($this_);
    }
}
