using System.Text.RegularExpressions;
using Tyhp.Domain.Services;
using Tyhp.Tests.TestHelpers;

namespace Tyhp.Tests.Domain.Services;

[Trait("Category", "Tyhpdef")]
public class TyhpdefOutputWriterTests
{
    [Fact]
    public void Write_EmitsHeaderAndAutoGeneratedComment()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile());

        output.Should().StartWith("<?tyhpdef\n");
        output.Should().Contain("AUTO-GENERATED, DO NOT EDIT");
        AssertParses(output);
    }

    [Fact]
    public void Write_FormatsConstantsFunctionsAndTypes()
    {
        var file = new TyhpdefFile
        {
            GlobalConstants =
            [
                new TyhpdefConstant { Name = "JSON_HEX_TAG", Type = "int" },
                new TyhpdefConstant { Name = "IMPORTED", Type = "int", Value = "0", UsesCoalesce = true },
            ],
            GlobalFunctions =
            [
                new TyhpdefFunction
                {
                    Name = "json_encode",
                    Parameters =
                    [
                        new TyhpdefParameter { Name = "value", Type = "mixed" },
                        new TyhpdefParameter { Name = "flags", Type = "int", DefaultValue = "0" },
                    ],
                    ReturnType = "string|false",
                },
            ],
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "JsonException",
                    Extends = "\\Exception",
                    Implements = ["\\Throwable", "\\Stringable"],
                    Constants = [new TyhpdefConstant { Name = "CODE", Type = "int", Modifiers = ["public"] }],
                    Properties =
                    [
                        new TyhpdefProperty { Name = "message", Type = "string", Modifiers = ["protected"] },
                    ],
                    Methods =
                    [
                        new TyhpdefMethod
                        {
                            Name = "__construct",
                            Modifiers = ["public"],
                            Parameters = [new TyhpdefParameter { Name = "message", Type = "string", DefaultValue = "\"\"" }],
                            ReturnType = "void",
                        },
                    ],
                },
                new TyhpdefClassDeclaration
                {
                    Kind = "interface",
                    Name = "JsonSerializable",
                    Methods =
                    [
                        new TyhpdefMethod { Name = "jsonSerialize", Modifiers = ["public"], ReturnType = "mixed" },
                    ],
                },
                new TyhpdefClassDeclaration
                {
                    Kind = "trait",
                    Name = "JsonHelpers",
                    Methods =
                    [
                        new TyhpdefMethod { Name = "toJson", Modifiers = ["public"], ReturnType = "string" },
                    ],
                },
                new TyhpdefClassDeclaration
                {
                    Kind = "enum",
                    Name = "Status",
                    BackingType = "string",
                    EnumCases =
                    [
                        new TyhpdefEnumCase { Name = "Active", BackingValue = "'active'" },
                        new TyhpdefEnumCase { Name = "Inactive", BackingValue = "'inactive'" },
                    ],
                    Methods =
                    [
                        new TyhpdefMethod { Name = "label", Modifiers = ["public"], ReturnType = "string" },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("const int JSON_HEX_TAG;");
        output.Should().Contain("const int IMPORTED ?? 0;");
        output.Should().Contain("function json_encode(mixed $value, int $flags = 0): string|false;");
        output.Should().Contain("class JsonException extends \\Exception implements \\Throwable, \\Stringable {");
        output.Should().Contain("public const int CODE;");
        output.Should().Contain("protected string $message;");
        output.Should().Contain("public function __construct(string $message = \"\"): void;");
        output.Should().Contain("interface JsonSerializable {");
        output.Should().Contain("public function jsonSerialize(): mixed;");
        output.Should().Contain("trait JsonHelpers {");
        output.Should().Contain("enum Status: string {");
        output.Should().Contain("case Active = 'active';");
        output.Should().Contain("case Inactive = 'inactive';");
        AssertParses(output);
    }

    [Fact]
    public void Write_HandlesEmptyClassInterfaceAndEnum()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration { Kind = "class", Name = "EmptyClass" },
                new TyhpdefClassDeclaration { Kind = "interface", Name = "EmptyInterface" },
                new TyhpdefClassDeclaration { Kind = "enum", Name = "EmptyEnum" },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("class EmptyClass {\n}");
        output.Should().Contain("interface EmptyInterface {\n}");
        output.Should().Contain("enum EmptyEnum {\n}");
        AssertParses(output);
    }

    [Fact]
    public void Write_UnsafeParameterDefault_KeepsOptionalWithNullDummy()
    {
        var file = new TyhpdefFile
        {
            GlobalFunctions =
            [
                new TyhpdefFunction
                {
                    Name = "concat",
                    Parameters =
                    [
                        new TyhpdefParameter { Name = "required", Type = "mixed" },
                        new TyhpdefParameter { Name = "suffix", Type = "string", DefaultValue = "'a'.'b'" },
                        new TyhpdefParameter { Name = "body", Type = "string", DefaultValue = "<<<'TXT'\nhi\nTXT" },
                        new TyhpdefParameter { Name = "stream", Type = "mixed", DefaultValue = "\\STDIN" },
                    ],
                    ReturnType = "void",
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain(
            "function concat(mixed $required, string $suffix = null, string $body = null, mixed $stream = null): void;");
        output.Should().NotContain("'a'.'b'");
        output.Should().NotContain("<<<");
        output.Should().NotContain("\\STDIN");
        AssertParses(output);
    }

    [Fact]
    public void Write_IncludesDocCommentsWhenEnabledAndOmitsWhenDisabled()
    {
        var file = new TyhpdefFile
        {
            GlobalFunctions =
            [
                new TyhpdefFunction
                {
                    Name = "strlen",
                    DocComment = "Returns the length of a string.",
                    Parameters = [new TyhpdefParameter { Name = "string", Type = "string" }],
                    ReturnType = "int",
                },
            ],
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Widget",
                    DocComment = "/**\n * A widget.\n */",
                },
            ],
        };

        var withDocs = TyhpdefOutputWriter.Write(file, includeDocComments: true);
        withDocs.Should().Contain("Returns the length of a string.");
        withDocs.Should().Contain("A widget.");
        AssertParses(withDocs);

        var withoutDocs = TyhpdefOutputWriter.Write(file, includeDocComments: false);
        withoutDocs.Should().NotContain("Returns the length of a string.");
        withoutDocs.Should().NotContain("A widget.");
        withoutDocs.Should().Contain("function strlen(string $string): int;");
        AssertParses(withoutDocs);
    }

    [Fact]
    public void Write_UntypedConstant_EmitsMixed()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            GlobalConstants =
            [
                new TyhpdefConstant { Name = "STDIN" },
            ],
        });

        output.Should().Contain("const mixed STDIN;");
        AssertParses(output);
    }

    [Fact]
    public void Write_DeprecatedClassName_PrefixesBackslash()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Deprecated",
                    Modifiers = ["final"],
                },
            ],
        });

        output.Should().Contain("final class \\Deprecated");
        output.Should().NotContain("final class Deprecated {");
        AssertParses(output);
    }

    [Fact]
    public void Write_ReservedClassConstant_UsesSelfAsEscape()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "WidgetDb",
                    Constants =
                    [
                        new TyhpdefConstant
                        {
                            Name = "FUNCTION",
                            Type = "int",
                            Value = "31",
                            UsesCoalesce = true,
                            Modifiers = ["public"],
                        },
                    ],
                },
            ],
        });

        output.Should().Contain("public const int self::FUNCTION as FUNCTION ?? 31;");
        AssertParses(output);
    }

    [Fact]
    public void Write_EmitsDeprecatedKeyword()
    {
        var file = new TyhpdefFile
        {
            GlobalConstants =
            [
                new TyhpdefConstant { Name = "OLD_FLAG", Type = "int", IsDeprecated = true },
            ],
            GlobalFunctions =
            [
                new TyhpdefFunction
                {
                    Name = "old_fn",
                    IsDeprecated = true,
                    ReturnType = "void",
                },
            ],
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "OldClass",
                    IsDeprecated = true,
                    Methods =
                    [
                        new TyhpdefMethod { Name = "legacy", Modifiers = ["public"], IsDeprecated = true, ReturnType = "void" },
                    ],
                    Properties =
                    [
                        new TyhpdefProperty { Name = "legacyProp", Type = "string", Modifiers = ["public"], IsDeprecated = true },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("deprecated const int OLD_FLAG;");
        output.Should().Contain("deprecated function old_fn(): void;");
        output.Should().Contain("deprecated class OldClass {");
        output.Should().Contain("deprecated public function legacy(): void;");
        output.Should().Contain("deprecated public string $legacyProp;");
        AssertParses(output);
    }

    [Fact]
    public void Write_WrapsNamespaceContentsWithIndent()
    {
        var file = new TyhpdefFile
        {
            Namespaces =
            [
                new TyhpdefNamespace
                {
                    Name = "App\\Widgets",
                    Constants = [new TyhpdefConstant { Name = "MAX", Type = "int" }],
                    Functions =
                    [
                        new TyhpdefFunction { Name = "make", ReturnType = "void" },
                    ],
                    Classes =
                    [
                        new TyhpdefClassDeclaration
                        {
                            Kind = "class",
                            Name = "Widget",
                            Properties =
                            [
                                new TyhpdefProperty { Name = "label", Type = "string", Modifiers = ["public"] },
                            ],
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("namespace App\\Widgets {");
        output.Should().Contain("    const int MAX;");
        output.Should().Contain("    function make(): void;");
        output.Should().Contain("    class Widget {");
        output.Should().Contain("        public string $label;");
        output.Should().NotContain("namespace \\App\\Widgets");
        AssertParses(output);
    }

    [Fact]
    public void Write_FormatsStructsTypeAliasesPartialAndClassAlias()
    {
        var file = new TyhpdefFile
        {
            TypeAliases =
            [
                new TyhpdefTypeAlias
                {
                    Name = "JsonMap",
                    AliasedType = "array<string, mixed>",
                    GenericParameters = [],
                },
            ],
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "struct",
                    Name = "CallableArgs1",
                    GenericParameters = [new TyhpdefGenericParameter { Name = "T1" }],
                    Properties = [new TyhpdefProperty { Name = "0 as $_1", Type = "T1" }],
                },
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "DateTime",
                    AsAlias = "DateTimeImmutable",
                    IsPartial = true,
                },
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Some\\Namespaced\\OldName",
                    AsAlias = "NewName",
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("type JsonMap = array<string, mixed>;");
        output.Should().Contain("type CallableArgs1<T1> = struct {");
        output.Should().Contain("T1 0 as $_1;");
        output.Should().Contain("partial class DateTime as DateTimeImmutable {");
        // `class PhpName as TyhpName`: PhpName is the FQN-capable `AliasOf=className` side and
        // must be backslash-qualified; TyhpName binds to a bare T_STRING and must not be.
        output.Should().Contain("class \\Some\\Namespaced\\OldName as NewName {");
        AssertParses(output);
    }

    [Fact]
    [Trait("Category", "Story27")]
    public void Write_ObjectShapeAlias_EmitsIntersectionAndMembers()
    {
        var file = new TyhpdefFile
        {
            TypeAliases =
            [
                new TyhpdefTypeAlias
                {
                    Name = "TimestampedLogger",
                    IntersectionTypes = ["\\Acme\\Log\\LoggerInterface"],
                    ObjectShape = new TyhpdefObjectShape
                    {
                        Methods =
                        [
                            new TyhpdefMethod
                            {
                                Name = "getLastLogAt",
                                Modifiers = ["public"],
                                ReturnType = "\\DateTimeImmutable",
                            },
                        ],
                    },
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("type TimestampedLogger = \\Acme\\Log\\LoggerInterface & object {");
        output.Should().Contain("public function getLastLogAt(): \\DateTimeImmutable;");
        output.Should().Contain("};");
        AssertParses(output);
    }

    [Fact]
    public void Write_KeywordClassName_PrefixesFqcn()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Isset",
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("class \\Isset {");
        output.Should().NotContain("class Isset {");
        AssertParses(output);
    }

    [Fact]
    public void Write_KeywordClassAlias_PrefixesPhpName()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Isset",
                    AsAlias = "IssetMatcher",
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("class \\Isset as IssetMatcher {");
        output.Should().NotContain("class Isset as IssetMatcher");
        AssertParses(output);
    }

    [Fact]
    public void Write_KeywordClassAlias_InNamespace_PrefixesEnclosingFqcn()
    {
        var file = new TyhpdefFile
        {
            Namespaces =
            [
                new TyhpdefNamespace
                {
                    Name = "Acme\\Probe",
                    Classes =
                    [
                        new TyhpdefClassDeclaration
                        {
                            Kind = "class",
                            Name = "Isset",
                            AsAlias = "IssetMatcher",
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("class \\Acme\\Probe\\Isset as IssetMatcher {");
        AssertParses(output);
    }

    [Fact]
    public void Write_KeywordExternFunction_InNamespace_PrefixesEnclosingFqcn()
    {
        var file = new TyhpdefFile
        {
            Namespaces =
            [
                new TyhpdefNamespace
                {
                    Name = "Some\\Ns",
                    Functions =
                    [
                        new TyhpdefFunction
                        {
                            Name = "isset",
                            IsExtern = true,
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("extern function \\Some\\Ns\\isset;");
        output.Should().NotContain("extern function \\isset;");
        AssertParses(output);
    }

    [Theory]
    [InlineData("isset")]
    [InlineData("Isset")]
    [InlineData("extends")]
    [InlineData("implements")]
    [InlineData("declare")]
    [InlineData("enddeclare")]
    [InlineData("endif")]
    [InlineData("endwhile")]
    [InlineData("endfor")]
    [InlineData("endforeach")]
    [InlineData("endswitch")]
    [InlineData("include_once")]
    [InlineData("require_once")]
    [InlineData("Is")]
    public void FormatDeclaredTypeName_PreviouslyMissingKeywordsUseEnclosingNamespace(string name)
    {
        TyhpdefOutputWriter.FormatDeclaredTypeName(name, "Acme\\Probe")
            .Should().Be("\\Acme\\Probe\\" + name);
        TyhpdefOutputWriter.IsTyhpdefKeywordTypeName(name).Should().BeTrue();
    }

    [Fact]
    public void FormatDeclaredTypeName_PrefixesEveryReservedNonModifiersAndSemiReservedSpelling()
    {
        var spellings = GrammarReservedTypeNameSpellings().ToList();
        spellings.Should().Contain("isset");
        spellings.Should().Contain("extends");
        spellings.Should().Contain("implements");
        spellings.Should().Contain("include_once");
        spellings.Should().Contain("require_once");
        spellings.Should().Contain("endswitch");
        spellings.Count.Should().BeGreaterThan(50);

        foreach (var spelling in spellings)
        {
            TyhpdefOutputWriter.IsTyhpdefKeywordTypeName(spelling).Should().BeTrue(
                "lexer must treat '{0}' as a non-T_STRING class name", spelling);
            TyhpdefOutputWriter.FormatDeclaredTypeName(spelling, "Ns")
                .Should().Be("\\Ns\\" + spelling, spelling);
        }

        TyhpdefOutputWriter.FormatDeclaredTypeName("Widget", "Ns").Should().Be("Widget");
        TyhpdefOutputWriter.IsTyhpdefKeywordTypeName("is").Should().BeTrue();
        TyhpdefOutputWriter.IsTyhpdefKeywordTypeName("Widget").Should().BeFalse();
    }

    [Fact]
    public void Write_HeaderOnlyPartialClass_EmitsSemicolonNotBody()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "SplObjectStorage",
                    IsPartial = true,
                    IsHeaderOnly = true,
                    GenericParameters =
                    [
                        new TyhpdefGenericParameter { Name = "TObject", Constraint = "object", Default = "object" },
                        new TyhpdefGenericParameter { Name = "TData", Default = "mixed" },
                    ],
                    Implements = ["\\Countable", "\\Iterator<int, TObject>"],
                },
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "SplObjectStorage",
                    IsPartial = true,
                    Methods =
                    [
                        new TyhpdefMethod
                        {
                            Name = "getInfo",
                            Modifiers = ["public"],
                            ReturnType = "TData",
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain(
            "partial class SplObjectStorage<TObject extends object = object, TData = mixed> implements \\Countable, \\Iterator<int, TObject>;");
        output.Should().Contain("partial class SplObjectStorage {");
        output.Should().Contain("function getInfo(): TData;");
        AssertParses(output);
    }

    [Fact]
    public void Write_FormatsClassBodyExtensionMembersAndOperators()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Money",
                    Operators =
                    [
                        new TyhpdefMethod
                        {
                            Name = "+",
                            Parameters =
                            [
                                new TyhpdefParameter { Name = "left", Type = "self" },
                                new TyhpdefParameter { Name = "right", Type = "self" },
                            ],
                            ReturnType = "self",
                        },
                    ],
                    ExtensionMembers =
                    [
                        new TyhpdefExtensionMember
                        {
                            Kind = "fn",
                            Name = "formatCurrency",
                            Parameters = [new TyhpdefParameter { Name = "locale", Type = "string", DefaultValue = "'en_US'" }],
                            ReturnType = "string",
                            Body = "$locale",
                        },
                        new TyhpdefExtensionMember
                        {
                            Kind = "fn",
                            Name = "shortLabel",
                            ReturnType = "string",
                            Body = "$this->formatCurrency()",
                        },
                        new TyhpdefExtensionMember
                        {
                            Kind = "operator",
                            Name = "+",
                            Parameters =
                            [
                                new TyhpdefParameter { Name = "left", Type = "self" },
                                new TyhpdefParameter { Name = "right", Type = "self" },
                            ],
                            ReturnType = "self",
                            Body = "$left",
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("operator +(self $left, self $right): self;");
        output.Should().Contain("extension fn formatCurrency(string $locale = 'en_US'): string => $locale;");
        output.Should().Contain("extension fn shortLabel(): string => $this->formatCurrency();");
        output.Should().Contain("extension operator +(self $left, self $right): self => $left;");
        output.Should().NotContain("#[\\Tyhp\\Optimize\\Inline]");
        output.Should().NotContain("extension function ");
        AssertParses(output);
    }

    [Fact]
    public void Write_FormatsStandaloneExtensionWithShortArrowMembers()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "extension",
                    Name = "StringExtensions",
                    Extends = "string",
                    ExtensionMembers =
                    [
                        new TyhpdefExtensionMember
                        {
                            Kind = "function",
                            Name = "length",
                            ReturnType = "int",
                            Body = "\\strlen($this)",
                        },
                        new TyhpdefExtensionMember
                        {
                            Kind = "operator",
                            Name = "*",
                            Parameters =
                            [
                                new TyhpdefParameter { Name = "left", Type = "self" },
                                new TyhpdefParameter { Name = "right", Type = "int" },
                            ],
                            ReturnType = "string",
                            Body = "$left",
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("extension StringExtensions extends string {");
        output.Should().Contain("fn length(): int => \\strlen($this);");
        output.Should().Contain("operator *(self $left, int $right): string => $left;");
        AssertParses(output);
    }

    [Fact]
    public void Write_FormatsStandaloneExtensionBlockTargetOnHeader()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "extension",
                    Name = "StringExtensions",
                    Extends = "string",
                    ExtensionMembers =
                    [
                        new TyhpdefExtensionMember
                        {
                            Kind = "fn",
                            Name = "length",
                            ReturnType = "int",
                            Body = "\\strlen($this)",
                        },
                        new TyhpdefExtensionMember
                        {
                            Kind = "operator",
                            Name = "*",
                            Parameters =
                            [
                                new TyhpdefParameter { Name = "left", Type = "self" },
                                new TyhpdefParameter { Name = "right", Type = "int" },
                            ],
                            ReturnType = "string",
                            Body = "\\str_repeat($left, $right)",
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("extension StringExtensions extends string {");
        output.Should().Contain("fn length(): int => \\strlen($this);");
        output.Should().Contain(
            "operator *(self $left, int $right): string => \\str_repeat($left, $right);");
        output.Should().NotContain("extends string $this");
        output.Should().NotContain("operator *<string>");
        AssertParses(output);
    }

    [Fact]
    public void Write_FormatsTrackCBackerStubAndCopiedExtensionMappings()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "StringHelpers",
                    AsAlias = "StringHelpers__tyhpExtensionBacker",
                    Methods =
                    [
                        new TyhpdefMethod
                        {
                            Name = "complexStringProcess",
                            Modifiers = ["public", "static"],
                            Parameters = [new TyhpdefParameter { Name = "$this_", Type = "string" }],
                            ReturnType = "string",
                        },
                        new TyhpdefMethod
                        {
                            Name = "simpleProcess",
                            Modifiers = ["public", "static"],
                            Parameters = [new TyhpdefParameter { Name = "$this_", Type = "string" }],
                            ReturnType = "string",
                        },
                    ],
                },
                new TyhpdefClassDeclaration
                {
                    Kind = "extension",
                    Name = "StringHelpers",
                    Extends = "string",
                    ExtensionMembers =
                    [
                        new TyhpdefExtensionMember
                        {
                            Kind = "fn",
                            Name = "complexStringProcess",
                            ReturnType = "string",
                            Body = "StringHelpers__tyhpExtensionBacker::complexStringProcess($this)",
                        },
                        new TyhpdefExtensionMember
                        {
                            Kind = "fn",
                            Name = "shortProcess",
                            ReturnType = "string",
                            Body = "' ' . $this",
                        },
                        new TyhpdefExtensionMember
                        {
                            Kind = "fn",
                            Name = "simpleProcess",
                            ReturnType = "string",
                            Body = "$this . ' '",
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("class StringHelpers as StringHelpers__tyhpExtensionBacker {");
        output.Should().Contain("public static function complexStringProcess(string $this_): string;");
        output.Should().Contain("public static function simpleProcess(string $this_): string;");
        output.Should().NotContain("function shortProcess(");
        output.Should().Contain("extension StringHelpers extends string {");
        output.Should().Contain(
            "fn complexStringProcess(): string => StringHelpers__tyhpExtensionBacker::complexStringProcess($this);");
        output.Should().Contain("fn shortProcess(): string => ' ' . $this;");
        output.Should().Contain("fn simpleProcess(): string => $this . ' ';");
        output.Should().NotContain("use extension");
        output.Should().NotContain("global use extension");
        AssertParses(output);
    }

    [Fact]
    public void Write_FormatsVariadicByRefAsyncAndExtensionFunction()
    {
        var file = new TyhpdefFile
        {
            GlobalFunctions =
            [
                new TyhpdefFunction
                {
                    Name = "array_map",
                    Parameters =
                    [
                        new TyhpdefParameter { Name = "callback", Type = "callable" },
                        new TyhpdefParameter { Name = "arrays", Type = "array", IsVariadic = true },
                    ],
                    ReturnType = "array",
                },
                new TyhpdefFunction
                {
                    Name = "preg_match",
                    ReturnsReference = true,
                    Parameters =
                    [
                        new TyhpdefParameter { Name = "matches", Type = "array", IsByReference = true },
                    ],
                    ReturnType = "int",
                },
                new TyhpdefFunction
                {
                    Name = "fetchValue",
                    IsAsync = true,
                    ReturnType = "int",
                },
                new TyhpdefFunction
                {
                    Name = "toCamelCase",
                    IsExtension = true,
                    Parameters = [new TyhpdefParameter { Name = "this", Type = "string" }],
                    ReturnType = "string",
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("function array_map(callable $callback, array ...$arrays): array;");
        output.Should().Contain("function &preg_match(array &$matches): int;");
        output.Should().Contain("async function fetchValue(): int;");
        output.Should().Contain("function toCamelCase(extends string $this): string;");
        AssertParses(output);
    }

    [Fact]
    public void Write_PrefixesFullyQualifiedNamesWithBackslash()
    {
        TyhpdefOutputWriter.FormatType("Foo\\Bar").Should().Be("\\Foo\\Bar");
        TyhpdefOutputWriter.FormatType("\\Foo\\Bar").Should().Be("\\Foo\\Bar");
        TyhpdefOutputWriter.FormatType("string").Should().Be("string");
        TyhpdefOutputWriter.FormatType("array<string, Foo\\Bar>").Should().Be("array<string, \\Foo\\Bar>");
        TyhpdefOutputWriter.FormatType("int|Foo\\Bar").Should().Be("int|\\Foo\\Bar");
    }

    [Fact]
    public void Write_DoesNotEmitPhpGatesWhenUnset()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration { Kind = "class", Name = "Plain" },
            ],
        });

        output.Should().NotContain("declare(php=");
        output.Should().NotContain("Tyhp\\Php");
        AssertParses(output);
    }

    [Fact]
    public void Write_ExternBareForm_OmitsKindKeyword()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "extern",
                    Name = "Acme\\Document",
                    IsExtern = true,
                    ProvidedBy = "tyhpdef/acme-search",
                },
            ],
        });

        output.Should().Contain("// @provided-by: tyhpdef/acme-search");
        output.Should().Contain("extern \\Acme\\Document;");
        output.Should().NotContain("extern class");
        AssertParses(output);
    }

    [Fact]
    public void Write_ExternClassForm_KeepsKindKeyword()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "WidgetHandle",
                    IsExtern = true,
                    ProvidedBy = "tyhpdef/acme-curl",
                },
            ],
        });

        output.Should().Contain("extern class WidgetHandle;");
        AssertParses(output);
    }

    [Fact]
    public void Write_ExternFunction_IsNameOnlyWithProvidedBy()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            GlobalFunctions =
            [
                new TyhpdefFunction
                {
                    Name = "\\widget_add",
                    IsExtern = true,
                    ProvidedBy = "tyhpdef/acme-math",
                },
            ],
        });

        output.Should().Contain("// @provided-by: tyhpdef/acme-math");
        output.Should().Contain("extern function \\widget_add;");
        output.Should().NotContain("function \\widget_add(");
        AssertParses(output);
    }

    [Fact]
    public void Write_ExternConst_IsNameOnlyWithProvidedBy()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            GlobalConstants =
            [
                new TyhpdefConstant
                {
                    Name = "\\WIDGET_ROUND_PLUSINF",
                    IsExtern = true,
                    ProvidedBy = "tyhpdef/acme-int",
                },
            ],
        });

        output.Should().Contain("// @provided-by: tyhpdef/acme-int");
        output.Should().Contain("extern const \\WIDGET_ROUND_PLUSINF;");
        AssertParses(output);
    }

    [Theory]
    [InlineData(">=8.4")]
    [InlineData("<8.4")]
    [InlineData(">=8.3 <8.4")]
    public void Write_DeclareBlock_WrapsBareVersionConstraint(string constraint)
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            DeclareBlocks =
            [
                new TyhpdefDeclareBlock
                {
                    Constraint = constraint,
                    Functions = [new TyhpdefFunction { Name = "gated", ReturnType = "void" }],
                },
            ],
        }, includeDocComments: false);

        output.Should().Contain($"declare(php=\"{constraint}\")");
        output.Should().NotContain($"declare({constraint})");
        AssertParses(output);
    }

    [Fact]
    public void Write_DeclareBlock_KeepsAlreadyKeyedPhpConstraint()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            DeclareBlocks =
            [
                new TyhpdefDeclareBlock
                {
                    Constraint = "php=\">=8.4\"",
                    Functions = [new TyhpdefFunction { Name = "gated", ReturnType = "void" }],
                },
            ],
        }, includeDocComments: false);

        output.Should().Contain("declare(php=\">=8.4\")");
        AssertParses(output);
    }

    [Fact]
    public void Write_SequenceReturnsOneStringPerFile()
    {
        var files = new[]
        {
            new TyhpdefFile { GlobalTypes = [new TyhpdefClassDeclaration { Kind = "class", Name = "A" }] },
            new TyhpdefFile { GlobalTypes = [new TyhpdefClassDeclaration { Kind = "class", Name = "B" }] },
        };

        var outputs = TyhpdefOutputWriter.Write(files);

        outputs.Should().HaveCount(2);
        outputs[0].Should().Contain("class A {");
        outputs[1].Should().Contain("class B {");
        AssertParses(outputs[0]);
        AssertParses(outputs[1]);
    }

    [Fact]
    public void Write_UsesCustomHeaderWhenProvided()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            Header = "Built using PHP v8.2.9\nEXT: json v8.2.9",
        });

        output.Should().Contain("AUTO-GENERATED, DO NOT EDIT");
        output.Should().Contain("Built using PHP v8.2.9");
        output.Should().Contain("EXT: json v8.2.9");
        AssertParses(output);
    }

    [Fact]
    public void Write_GenericConstraintEmitsDefault()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Box",
                    GenericParameters =
                    [
                        new TyhpdefGenericParameter
                        {
                            Name = "TValue",
                            Constraint = "int|float|string",
                            Default = "string",
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("class Box<TValue extends int|float|string = string> {");
        AssertParses(output);
    }

    [Fact]
    public void Write_DropsFieldsTheTyhpdefGrammarCannotExpress()
    {
        // These IR fields are documented (§5.1) but have no corresponding tyhpdef grammar
        // syntax in their given context. The writer must silently drop them instead of
        // emitting a construct the parser rejects (AC: "parses without errors").
        var file = new TyhpdefFile
        {
            GlobalConstants =
            [
                // tyhpdefImportConstStatement has no Modifiers slot.
                new TyhpdefConstant { Name = "NO_MODS", Type = "int", Modifiers = ["public"] },
            ],
            GlobalFunctions =
            [
                // tyhpdefImportFunctionDeclarationStatement has no Modifiers slot.
                new TyhpdefFunction { Name = "no_mods_fn", Modifiers = ["static"], ReturnType = "void" },
            ],
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    // tyhpdefImportTraitDeclarationStatement has neither Modifiers, Extends,
                    // nor Implements.
                    Kind = "trait",
                    Name = "NoModsTrait",
                    Modifiers = ["abstract"],
                    Extends = "\\SomeBase",
                    Implements = ["\\SomeInterface"],
                },
                new TyhpdefClassDeclaration
                {
                    // tyhpdefImportInterfaceDeclarationStatement / EnumDeclarationStatement have
                    // no Modifiers slot either.
                    Kind = "interface",
                    Name = "NoModsInterface",
                    Modifiers = ["abstract"],
                },
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "HostClass",
                    Properties =
                    [
                        // Bodyless hook lists are the tyhpdef form; attributes stay on the property.
                        new TyhpdefProperty
                        {
                            Name = "value",
                            Type = "string",
                            Attributes = [new TyhpdefAttribute { Name = "\\SomeAttr" }],
                            Hooks =
                            [
                                new TyhpdefPropertyHook { Name = "get" },
                                new TyhpdefPropertyHook { Name = "set" },
                            ],
                        },
                    ],
                    Operators =
                    [
                        // tyhpdefClassOperator has no modifiers/async/generics/attributes/PhpGate.
                        new TyhpdefMethod
                        {
                            Name = "+",
                            Modifiers = ["public"],
                            IsAsync = true,
                            GenericParameters = [new TyhpdefGenericParameter { Name = "T" }],
                            Attributes = [new TyhpdefAttribute { Name = "\\SomeAttr" }],
                            PhpGate = ">=8.3",
                            Parameters =
                            [
                                new TyhpdefParameter { Name = "left", Type = "self" },
                                new TyhpdefParameter { Name = "right", Type = "self" },
                            ],
                            ReturnType = "self",
                        },
                    ],
                    Methods =
                    [
                        new TyhpdefMethod
                        {
                            Name = "doThing",
                            Modifiers = ["public"],
                            Attributes = [new TyhpdefAttribute { Name = "\\SomeAttr" }],
                            PhpGate = ">=8.3",
                            ReturnType = "void",
                        },
                    ],
                },
                new TyhpdefClassDeclaration
                {
                    // tyhpStructDeclarationStatement has no `partial` support.
                    Kind = "struct",
                    Name = "NoPartialStruct",
                    IsPartial = true,
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().NotContain("public const int NO_MODS");
        output.Should().NotContain("static function no_mods_fn");
        output.Should().NotContain("abstract trait");
        output.Should().NotContain("trait NoModsTrait extends");
        output.Should().NotContain("trait NoModsTrait implements");
        output.Should().NotContain("abstract interface");
        output.Should().Contain("public string $value { get; set; }");
        output.Should().NotContain("public operator");
        output.Should().NotContain("async operator");
        output.Should().NotContain("operator +<T>");
        output.Should().NotContain("partial struct");
        output.Should().Contain("operator +(self $left, self $right): self;");
        output.Should().Contain("#[\\Tyhp\\Php(\">=8.3\")]");
        output.Should().Contain("public function doThing(): void;");
        output.Should().Contain("SomeAttr");
        AssertParses(output);
    }

    [Fact]
    public void Write_OmitsHookListWhenHooksEmpty()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Holder",
                    Properties =
                    [
                        new TyhpdefProperty
                        {
                            Name = "name",
                            Type = "string",
                            Modifiers = ["public"],
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("public string $name;");
        output.Should().NotContain("get;");
        output.Should().NotContain("set;");
        AssertParses(output);
    }

    [Fact]
    public void Write_EmitsGetSetAndByRefGetHookLists()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Holder",
                    Properties =
                    [
                        new TyhpdefProperty
                        {
                            Name = "hooked",
                            Type = "string",
                            Modifiers = ["public"],
                            Hooks =
                            [
                                new TyhpdefPropertyHook { Name = "get" },
                                new TyhpdefPropertyHook { Name = "set" },
                            ],
                        },
                        new TyhpdefProperty
                        {
                            Name = "items",
                            Type = "array",
                            Modifiers = ["public"],
                            Hooks =
                            [
                                new TyhpdefPropertyHook { Name = "get", ReturnsRef = true },
                                new TyhpdefPropertyHook { Name = "set" },
                            ],
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("public string $hooked { get; set; }");
        output.Should().Contain("public array $items { &get; set; }");
        AssertParses(output);
    }

    [Fact]
    public void Write_EmitsGetOnlyHookList()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Holder",
                    Properties =
                    [
                        new TyhpdefProperty
                        {
                            Name = "hookedCount",
                            Type = "int",
                            Modifiers = ["public"],
                            Hooks = [new TyhpdefPropertyHook { Name = "get" }],
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("public int $hookedCount { get; }");
        AssertParses(output);
    }

    [Fact]
    public void Write_EmitsHookModifierBeforeByRefAmpersand()
    {
        // Grammar order is Modifiers=propertyHookModifiers ReturnsRef=returnsRef Identifier=identifier
        // (`tyhpdefPropertyHook`); the writer must match that token order, not attribute-then-ref-then-modifier.
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Holder",
                    Properties =
                    [
                        new TyhpdefProperty
                        {
                            Name = "items",
                            Type = "array",
                            Modifiers = ["public"],
                            Hooks =
                            [
                                new TyhpdefPropertyHook { Name = "get", ReturnsRef = true, Modifiers = ["final"] },
                                new TyhpdefPropertyHook { Name = "set" },
                            ],
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("public array $items { final &get; set; }");
        AssertParses(output);
    }

    [Fact]
    public void Write_EmitsHookVisibilityAndAttributes()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Holder",
                    Properties =
                    [
                        new TyhpdefProperty
                        {
                            Name = "name",
                            Type = "string",
                            Modifiers = ["public"],
                            Hooks =
                            [
                                new TyhpdefPropertyHook { Name = "get" },
                                new TyhpdefPropertyHook { Name = "set", Modifiers = ["private"] },
                            ],
                        },
                        new TyhpdefProperty
                        {
                            Name = "attributed",
                            Type = "string",
                            Modifiers = ["public"],
                            Hooks =
                            [
                                new TyhpdefPropertyHook
                                {
                                    Name = "get",
                                    Attributes = [new TyhpdefAttribute { Name = "Attr" }],
                                },
                                new TyhpdefPropertyHook { Name = "set" },
                            ],
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("public string $name { get; private set; }");
        output.Should().Contain("public string $attributed { #[Attr] get; set; }");
        AssertParses(output);
    }

    [Fact]
    public void Write_DoesNotEmitHookListOnStructProperties()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "struct",
                    Name = "Point",
                    Properties =
                    [
                        new TyhpdefProperty
                        {
                            Name = "x",
                            Type = "int",
                            Hooks =
                            [
                                new TyhpdefPropertyHook { Name = "get" },
                                new TyhpdefPropertyHook { Name = "set" },
                            ],
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("int $x;");
        output.Should().NotContain("get;");
        output.Should().NotContain("set;");
        AssertParses(output);
    }

    [Fact]
    public void Write_CleansExcessiveBlankLines()
    {
        var output = TyhpdefOutputWriter.Write(new TyhpdefFile
        {
            GlobalTypes = [new TyhpdefClassDeclaration { Kind = "class", Name = "A" }],
        });

        output.Should().NotContain("\n\n\n");
        output.Should().NotContain("{\n\n");
    }

    [Fact]
    public void Write_PropertyCoalesceValue_EmitsDoubleQuestionNotEquals()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Bag",
                    Properties =
                    [
                        new TyhpdefProperty
                        {
                            Name = "items",
                            Type = "array",
                            Modifiers = ["public"],
                            CoalesceValue = "[]",
                        },
                        new TyhpdefProperty
                        {
                            Name = "logger",
                            Type = "?\\Acme\\Log\\LoggerInterface",
                            Modifiers = ["protected"],
                            CoalesceValue = "null",
                        },
                        new TyhpdefProperty
                        {
                            Name = "plain",
                            Type = "string",
                            Modifiers = ["public"],
                        },
                    ],
                    Methods =
                    [
                        new TyhpdefMethod
                        {
                            Name = "__construct",
                            Modifiers = ["public"],
                            Parameters =
                            [
                                new TyhpdefParameter
                                {
                                    Name = "count",
                                    Type = "int",
                                    DefaultValue = "0",
                                    IsPromoted = true,
                                },
                            ],
                            ReturnType = "void",
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("public array $items ?? [];");
        output.Should().Contain("protected ?\\Acme\\Log\\LoggerInterface $logger ?? null;");
        output.Should().Contain("public string $plain;");
        output.Should().Contain("public function __construct(int $count = 0): void;");
        output.Should().NotContain("$items =");
        output.Should().NotContain("$logger =");
        output.Should().NotContain("function __construct(public int $count");
        AssertParses(output);
    }

    [Fact]
    public void Write_HookedPropertyCoalesceValue_EmitsBeforeHooks()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Holder",
                    Properties =
                    [
                        new TyhpdefProperty
                        {
                            Name = "name",
                            Type = "string",
                            Modifiers = ["public"],
                            CoalesceValue = "'x'",
                            Hooks =
                            [
                                new TyhpdefPropertyHook { Name = "get" },
                                new TyhpdefPropertyHook { Name = "set" },
                            ],
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("public string $name ?? 'x' { get; set; }");
        output.Should().NotContain("$name =");
        AssertParses(output);
    }

    [Fact]
    public void Write_PromotedPropertyAndParam_SplitCoalesceAndEquals()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Counter",
                    Properties =
                    [
                        new TyhpdefProperty
                        {
                            Name = "count",
                            Type = "int",
                            Modifiers = ["public"],
                            CoalesceValue = "0",
                        },
                    ],
                    Methods =
                    [
                        new TyhpdefMethod
                        {
                            Name = "__construct",
                            Modifiers = ["public"],
                            Parameters =
                            [
                                new TyhpdefParameter
                                {
                                    Name = "count",
                                    Type = "int",
                                    DefaultValue = "0",
                                    IsPromoted = true,
                                },
                            ],
                            ReturnType = "void",
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("public int $count ?? 0;");
        output.Should().Contain("public function __construct(int $count = 0): void;");
        output.Should().NotContain("public int $count = 0;");
        AssertParses(output);
    }

    [Fact]
    public void Write_EmitsDocblockThenAttributesThenDeclaration()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "class",
                    Name = "Widget",
                    DocComment = "A widget.",
                    PhpGate = ">=8.4",
                    Attributes = [new TyhpdefAttribute { Name = "\\Deprecated" }],
                    Methods =
                    [
                        new TyhpdefMethod
                        {
                            Name = "run",
                            Modifiers = ["public"],
                            DocComment = "Runs the widget.",
                            PhpGate = ">=8.4",
                            Attributes = [new TyhpdefAttribute { Name = "\\SensitiveParameter" }],
                            ReturnType = "void",
                        },
                    ],
                    Properties =
                    [
                        new TyhpdefProperty
                        {
                            Name = "label",
                            Type = "string",
                            Modifiers = ["public"],
                            DocComment = "Display label.",
                            PhpGate = ">=8.4",
                            Attributes = [new TyhpdefAttribute { Name = "\\AllowDynamicProperties" }],
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        AssertDecorationOrder(output, "A widget.", "#[\\Tyhp\\Php(\">=8.4\")]", "#[\\Deprecated]", "class Widget");
        AssertDecorationOrder(output, "Runs the widget.", "#[\\Tyhp\\Php(\">=8.4\")]", "#[\\SensitiveParameter]", "public function run(): void;");
        AssertDecorationOrder(output, "Display label.", "#[\\Tyhp\\Php(\">=8.4\")]", "#[\\AllowDynamicProperties]", "public string $label;");
        AssertParses(output);
    }

    private static IEnumerable<string> GrammarReservedTypeNameSpellings()
    {
        var grammarDir = Path.Combine(
            TestFileManager.GetRepoRoot(),
            "Tyhp",
            "TyhpLang",
            "Grammar");
        // reservedNonModifiersBase / semiReservedBase are PHP rules shared via
        // `// #include` (see shared/PhpParser.reached.g4); PhpParser.g4 itself
        // only keeps the rules the tyhpdef closure does not reach.
        var grammar = File.ReadAllText(Path.Combine(grammarDir, "PhpParser.g4"))
            + File.ReadAllText(Path.Combine(grammarDir, "shared", "PhpParser.reached.g4"));
        var tokens = ExtractRuleTokens(grammar, "reservedNonModifiersBase")
            .Concat(ExtractRuleTokens(grammar, "semiReservedBase"))
            .Distinct(StringComparer.Ordinal);
        foreach (var token in tokens)
        {
            foreach (var spelling in SpellingsForGrammarToken(token))
            {
                yield return spelling;
            }
        }
    }

    private static IReadOnlyList<string> ExtractRuleTokens(string grammar, string ruleName)
    {
        var needle = "\n" + ruleName + "\n";
        var start = grammar.IndexOf(needle, StringComparison.Ordinal);
        start.Should().BeGreaterThanOrEqualTo(0, "missing grammar rule {0}", ruleName);
        var bodyStart = start + needle.Length;
        var endMatch = Regex.Match(grammar[bodyStart..], @"\n[ \t]*;");
        endMatch.Success.Should().BeTrue("unterminated grammar rule {0}", ruleName);
        var body = grammar.Substring(bodyStart, endMatch.Index);
        var matches = Regex.Matches(body, @"TokenValue=T_([A-Z0-9_]+)");
        matches.Count.Should().BeGreaterThan(0, "no tokens in grammar rule {0}", ruleName);
        return matches.Select(match => match.Groups[1].Value).ToList();
    }

    /// <summary>
    /// Token-name → source spelling. Underscored <c>T_INCLUDE_ONCE</c> names lowercased;
    /// only tokens whose lexer spelling is not the token name need exceptions
    /// (<c>T_LOGICAL_OR</c> is <c>or</c>, magic constants, <c>T_EXIT</c> is <c>exit</c>/<c>die</c>).
    /// </summary>
    private static IReadOnlyList<string> SpellingsForGrammarToken(string tokenName)
        => tokenName switch
        {
            "LOGICAL_OR" => ["or"],
            "LOGICAL_AND" => ["and"],
            "LOGICAL_XOR" => ["xor"],
            "EXIT" => ["exit", "die"],
            "CLASS_C" => ["__CLASS__"],
            "TRAIT_C" => ["__TRAIT__"],
            "FUNC_C" => ["__FUNCTION__"],
            "METHOD_C" => ["__METHOD__"],
            "LINE" => ["__LINE__"],
            "FILE" => ["__FILE__"],
            "DIR" => ["__DIR__"],
            "NS_C" => ["__NAMESPACE__"],
            "PROPERTY_C" => ["__PROPERTY__"],
            _ => [tokenName.ToLowerInvariant()],
        };

    private static void AssertDecorationOrder(string output, string docSnippet, string phpGate, string attribute, string declaration)
    {
        var doc = output.IndexOf(docSnippet, StringComparison.Ordinal);
        doc.Should().BeGreaterThanOrEqualTo(0, "missing doc snippet {0} in:\n{1}", docSnippet, output);

        var gate = output.IndexOf(phpGate, doc, StringComparison.Ordinal);
        gate.Should().BeGreaterThan(doc, "PHP gate should follow the docblock in:\n{0}", output);

        var attr = output.IndexOf(attribute, gate, StringComparison.Ordinal);
        attr.Should().BeGreaterThan(gate, "attribute should follow the PHP gate in:\n{0}", output);

        var decl = output.IndexOf(declaration, attr, StringComparison.Ordinal);
        decl.Should().BeGreaterThan(attr, "declaration should follow attributes in:\n{0}", output);
    }

    [Fact]
    public void Write_FormatsNestedExtensionGroupsAndByRefReceiver()
    {
        var file = new TyhpdefFile
        {
            GlobalTypes =
            [
                new TyhpdefClassDeclaration
                {
                    Kind = "extension",
                    Name = "ArrayExtensions",
                    ExtensionGroups =
                    [
                        new TyhpdefExtensionGroup
                        {
                            TargetType = "array<TKey, TValue>",
                            GenericParameters =
                            [
                                new TyhpdefGenericParameter { Name = "TKey", Constraint = "int|string" },
                                new TyhpdefGenericParameter { Name = "TValue" },
                            ],
                            Members =
                            [
                                new TyhpdefExtensionMember
                                {
                                    Kind = "fn",
                                    Name = "sort",
                                    ByRefReceiver = true,
                                    Parameters = [new TyhpdefParameter { Name = "flags", Type = "int" }],
                                    ReturnType = "bool",
                                    Body = "\\sort($this, $flags)",
                                },
                            ],
                        },
                    ],
                },
            ],
        };

        var output = TyhpdefOutputWriter.Write(file);

        output.Should().Contain("extension ArrayExtensions {");
        output.Should().Contain("extends<TKey extends int|string, TValue> array<TKey, TValue> {");
        output.Should().Contain("fn sort(&$this, int $flags): bool => \\sort($this, $flags);");
        output.Should().NotContain("extends array");
        AssertParses(output);
    }

    private static void AssertParses(string tyhpdef)
    {
        var result = ParserTestHelper.ParseTyhpdefContent(tyhpdef);
        result.Diagnostics.Errors.Should().BeEmpty(
            string.Join("; ", result.Diagnostics.Errors.Select(e => $"{e.Code} ({e.Line}:{e.Column}): {e.Message}"))
            + "\n--- generated ---\n" + tyhpdef);
        result.Ast.Should().NotBeNull();
    }
}
