<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function make(): void
{
    $cfg = new Config();
    $cfg->name = "test";
    $cfg->value = 42;
}

function copyConfig(\App\Config $cfg): \App\Config
{
    return \Tyhp\ObjectHelper::with(clone $cfg, ['name' => "updated"]);
}
