// #class PhpParserAstVisitor
// #using Antlr4.Runtime
// #using Antlr4.Runtime.Misc
// #using Tyhp.Domain.Exceptions
// #using Tyhp.TyhpLang.Ast
// #using Tyhp.TyhpLang.Ast.Interfaces
// #using Tyhp.TyhpLang.Parser


        public override TokenValueAst? VisitIsVariadic([NotNull] TyhpParser.IsVariadicContext context)
            => context.TokenValue != null ? this.GetTokenValueAst(context, context.TokenValue) : null;
