namespace Tyhp.Domain.Services
{
    /// <summary>
    /// Paths, headers, and naming for <c>generate_tyhpdef --vendor</c>.
    /// Output is always project <c>vendor-tyhpdef/</c>, never <c>tyhpdef/</c> or <c>vendor/</c>.
    /// </summary>
    public static class VendorTyhpdefLayout
    {
        public const string DirectoryName = "vendor-tyhpdef";

        public const string CompilerPackageName = "tyhp/compiler";

        public const string VendorRunningEnvironmentVariable = "TYHP_VENDOR_TYHPDEF_RUNNING";

        public const string NoVendorEnvironmentVariable = "TYHP_NO_VENDOR_TYHPDEF";

        public const string IdentityStampPrefix = "// @vendor-identity: ";

        public const string TyhpdefVendorPrefix = "tyhpdef/";

        public const string PhpExtCompanionPrefix = TyhpdefVendorPrefix + "php-ext-";

        /// <summary>
        /// Locked generated-file header (meaning, not localization). A fourth stamp line is
        /// appended by <see cref="BuildHeader"/>.
        /// </summary>
        public const string DoNotEditHeader =
            "// Generated by `tyhp generate_tyhpdef --vendor`. Do not edit this file.\n"
            + "// Re-running --vendor overwrites it. Put lasting changes in overlay tyhpdefs\n"
            + "// (tyhp.json \"overlay\", or `tyhp overlay create`), not in vendor-tyhpdef/.";

        /// <summary>
        /// Always-present extensions shipped by <c>tyhpdef/php</c>
        /// (<c>extra.tyhp.extensions</c>). Case-insensitive compare against <c>ext-*</c> names.
        /// </summary>
        public static readonly HashSet<string> AlwaysPresentPhpExtensions =
            new(StringComparer.OrdinalIgnoreCase)
            {
                "Core",
                "date",
                "filter",
                "hash",
                "json",
                "libxml",
                "pcre",
                "random",
                "Reflection",
                "SPL",
                "standard",
            };

        public static readonly string[] RuntimeRequirePackages =
        [
            "tyhp/core",
            "tyhp/async",
            "tyhp/lambda",
            "tyhp/decimal",
        ];

        public static readonly string[] TyhpdefRequireDevPackages =
        [
            "tyhpdef/php",
        ];

        public static string OutputDirectory(string projectRoot)
            => Path.Combine(projectRoot, DirectoryName);

        /// <summary>
        /// Public companion Composer name: <c>tyhpdef/&lt;vendor&gt;-&lt;name&gt;</c> with <c>/</c> → <c>-</c>.
        /// </summary>
        public static string LibraryCompanionName(string composerPackageName)
        {
            var trimmed = (composerPackageName ?? "").Trim().Trim('/');
            return TyhpdefVendorPrefix + trimmed.Replace('/', '-');
        }

        /// <summary>
        /// Implementation companion: <c>tyhpdef/&lt;vendor&gt;-&lt;name&gt;-impl</c>.
        /// Apps and <c>--vendor</c> do not root-require this name.
        /// </summary>
        public static string ImplCompanionName(string composerPackageName)
            => LibraryCompanionName(composerPackageName) + "-impl";

        /// <summary>
        /// True for <c>tyhpdef/&lt;vendor&gt;-&lt;name&gt;-impl</c>. The public metapackage is the root require.
        /// </summary>
        public static bool IsImplPackageName(string? name)
            => !string.IsNullOrEmpty(name)
                && name.StartsWith(TyhpdefVendorPrefix, StringComparison.OrdinalIgnoreCase)
                && name.EndsWith("-impl", StringComparison.OrdinalIgnoreCase);

        public static bool IsTyhpdefPackage(string? name)
            => !string.IsNullOrEmpty(name)
                && name.StartsWith(TyhpdefVendorPrefix, StringComparison.OrdinalIgnoreCase);

        /// <summary>
        /// Runtime <c>tyhp/*</c> packages or tyhpdef companion/stub packages.
        /// </summary>
        public static bool IsFirstPartyComposerPackage(string? name)
            => !string.IsNullOrEmpty(name)
                && (name.StartsWith("tyhp/", StringComparison.OrdinalIgnoreCase)
                    || name.StartsWith(TyhpdefVendorPrefix, StringComparison.OrdinalIgnoreCase));

        public static string PhpExtCompanionName(string extensionName)
            => PhpExtCompanionPrefix + (extensionName ?? "").Trim();

        public static string PackageStubFileName(string composerPackageName)
            => TyhpdefOutputLayout.PackageFileName(composerPackageName);

        public static string PackageExternsFileName(string composerPackageName)
        {
            var primary = PackageStubFileName(composerPackageName);
            var stem = Path.GetFileNameWithoutExtension(primary);
            return stem + ".externs.tyhpdef";
        }

        public static string ExtensionStubFileName(string extensionName)
            => TyhpdefOutputLayout.ExtensionFileName(extensionName);

        public static string Identity(string packageOrExtension, string version)
            => packageOrExtension.Trim() + "@" + version.Trim();

        public static string BuildHeader(string identity)
            => DoNotEditHeader + "\n" + IdentityStampPrefix + identity.Trim();

        public static bool FileHasMatchingIdentity(string path, string identity)
        {
            if (!File.Exists(path))
            {
                return false;
            }

            var expected = IdentityStampPrefix + identity.Trim();
            foreach (var raw in File.ReadLines(path))
            {
                var line = raw.Trim();
                if (line.Equals(expected, StringComparison.Ordinal))
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// Inserts or replaces the vendor header immediately after <c>&lt;?tyhpdef</c>.
        /// </summary>
        public static void StampGeneratedFile(string path, string identity)
        {
            if (!File.Exists(path))
            {
                return;
            }

            var original = File.ReadAllText(path);
            var stamped = ApplyHeader(original, identity);
            if (!string.Equals(original, stamped, StringComparison.Ordinal))
            {
                File.WriteAllText(path, stamped);
            }
        }

        internal static string ApplyHeader(string text, string identity)
        {
            var normalized = text.Replace("\r\n", "\n", StringComparison.Ordinal);
            var header = BuildHeader(identity).Replace("\r\n", "\n", StringComparison.Ordinal);
            const string open = "<?tyhpdef";
            var start = normalized.IndexOf(open, StringComparison.Ordinal);
            if (start < 0)
            {
                return header + "\n" + normalized.TrimStart();
            }

            var afterOpen = start + open.Length;
            if (afterOpen < normalized.Length && normalized[afterOpen] == '\n')
            {
                afterOpen++;
            }

            var rest = normalized[afterOpen..];
            rest = StripExistingVendorHeader(rest);
            return normalized[..afterOpen] + header + "\n" + rest.TrimStart('\n');
        }

        private static string StripExistingVendorHeader(string rest)
        {
            var lines = rest.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
            var i = 0;
            while (i < lines.Length)
            {
                var trimmed = lines[i].Trim();
                if (trimmed.StartsWith("// Generated by `tyhp generate_tyhpdef --vendor`", StringComparison.Ordinal)
                    || trimmed.StartsWith("// Re-running --vendor", StringComparison.Ordinal)
                    || trimmed.StartsWith("// (tyhp.json \"overlay\"", StringComparison.Ordinal)
                    || trimmed.StartsWith(IdentityStampPrefix, StringComparison.Ordinal))
                {
                    i++;
                    continue;
                }

                break;
            }

            return string.Join('\n', lines.Skip(i));
        }

        public static bool IsEnvironmentFlagSet(string? value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return false;
            }

            var trimmed = value.Trim();
            return trimmed == "1"
                || trimmed.Equals("true", StringComparison.OrdinalIgnoreCase)
                || trimmed.Equals("yes", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Wrapper version pin compatible with installed upstream
        /// (<c>3.10.0</c> → <c>3.10.0.0</c>). Null when the upstream version cannot be mapped
        /// (e.g. <c>dev-*</c> branch aliases).
        /// </summary>
        public static string? CompanionConstraintForUpstream(string installedVersion)
        {
            var raw = (installedVersion ?? "").Trim();
            if (raw.Length == 0)
            {
                return null;
            }

            if (raw.StartsWith("v", StringComparison.OrdinalIgnoreCase)
                && raw.Length > 1
                && char.IsDigit(raw[1]))
            {
                raw = raw[1..];
            }

            if (raw.StartsWith("dev-", StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }

            var plus = raw.IndexOf('+');
            if (plus >= 0)
            {
                raw = raw[..plus];
            }

            var dash = IndexOfPrereleaseDash(raw);
            var core = dash >= 0 ? raw[..dash] : raw;
            var pre = dash >= 0 ? raw[dash..] : "";
            if (core.Length == 0 || !char.IsDigit(core[0]))
            {
                return null;
            }

            return core + ".0" + pre;
        }

        public static bool CompanionVersionMatchesUpstream(string companionVersion, string upstreamVersion)
        {
            var companion = StripVersionPrefix(companionVersion);
            var upstream = StripVersionPrefix(upstreamVersion);
            if (companion.Length == 0 || upstream.Length == 0)
            {
                return false;
            }

            if (companion.Equals(upstream, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            return companion.StartsWith(upstream + ".", StringComparison.OrdinalIgnoreCase);
        }

        private static int IndexOfPrereleaseDash(string version)
        {
            for (var i = 0; i < version.Length; i++)
            {
                if (version[i] == '-' && i > 0 && char.IsDigit(version[i - 1]))
                {
                    return i;
                }
            }

            return -1;
        }

        private static string StripVersionPrefix(string version)
        {
            var raw = (version ?? "").Trim();
            if (raw.StartsWith("v", StringComparison.OrdinalIgnoreCase)
                && raw.Length > 1
                && char.IsDigit(raw[1]))
            {
                raw = raw[1..];
            }

            var plus = raw.IndexOf('+');
            return plus >= 0 ? raw[..plus] : raw;
        }
    }
}
