<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function answer(): \Tyhp\Promise
{
    return \Tyhp\Promise::_async(function (): int {
        return 42;
    });
}

function getAnswer(): \Tyhp\Promise
{
    return \Tyhp\Promise::_async(function (): int {
        return \Tyhp\Promise::_await(answer());
    });
}
