<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

function testHideAndAlias(): string
{
    $s = "Hello";
    return \mb_strtoupper($s);
}

function testVisibleLength(): int
{
    $s = "Hello";
    return \mb_strlen($s);
}
