<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function always_present(): void {}

function from_83(): void {}

function example(string $v): mixed
{
    return $v;
}
