<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App\Lower;

function wrap(string $s): string
{
    return ("[" . $s) . "]";
}

function shout(string $s): string
{
    return $s . "!";
}

function pipeFcc(string $s): string
{
    return wrap($s);
}

function pipeChain(string $s): string
{
    return shout(wrap($s));
}

function pipeArrow(string $s): string
{
    return (fn(string $x): string => wrap($x))($s);
}

function pipeVariableCallable(string $s): mixed
{
    $f = fn(string $x): string => wrap($x);
    return $f($s);
}

function pipeArrowThenFcc(string $s): string
{
    return wrap((fn(string $x): string => shout($x))($s));
}

function identity(int $n): int
{
    return $n;
}

function pipePrecedenceLeft(): int
{
    return identity(5 + 2);
}
