<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function demo(): void
{
    $method = 'GET';
    $typeName = 'int';
    $union = 'int|string';
    $plain = $method;
}
