<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function origin(): array
{
    return ['x' => 0, 'y' => 0];
}

function usePoint(array $p): int
{
    return $p['x'];
}
