<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

class Box
{
    use \Tyhp\Concerns\HasGenerics;

    private static ?\ReflectionClass $__reflectedClass__tyhpGeneric = null;
    private mixed $item = null {
        set(mixed $value) {
            $this->__tyhpGeneric->checkProperty('item', $value);
            $this->item = $value;
        }
    }
    public function __construct()
    {
        $this->tyhpBootTraits();
        if ($this->__tyhpGeneric->needsInit()) {
            self::__initGenerics__tyhpGeneric(null);
        }
        $this->__tyhpGeneric->enablePropertyChecks();
    }
    final public static function new_App_Box__tyhpGeneric(?\Tyhp\Type $__generic_T): self
    {
        self::$__reflectedClass__tyhpGeneric ??= new \ReflectionClass(self::class);
        $__tyhp_obj = self::$__reflectedClass__tyhpGeneric->newInstanceWithoutConstructor();
        $__tyhp_obj->__initGenerics__tyhpGeneric($__generic_T);
        $__tyhp_obj->__construct();
        return $__tyhp_obj;
    }
    public function set(mixed $value): void
    {
        $this->item = $value;
    }
    public function get(): mixed
    {
        return $this->item;
    }
    protected function __initGenerics__tyhpGeneric(?\Tyhp\Type ...$generics): void
    {
        $this->tyhpBootTraits();
        if ($this->__tyhpGeneric->isInitialized(\App\Box::class)) {
            return;
        }
        $t = $generics[0] ?? \Tyhp\Type::mixed();
        $this->__tyhpGeneric->init(static::class, \App\Box::class, new \Tyhp\NamedType('T', $t));
        $this->__tyhpGeneric->setPropertyType('item', \Tyhp\Type::nullable($t));
        $this->__tyhpGeneric->markBound();
    }
}
