<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

class User
{
    public string $name = "";
    public static function NameType(): \Tyhp\Type
    {
        return \Tyhp\Type::string();
    }
    public function getId(): int
    {
        return 42;
    }
}
