<?php

/**
 * Generated by Tyhp compiler.
 */

declare(strict_types=1);

namespace App;

function main(): void
{
    $p = ['x' => 0, 'y' => 0];
    $p['x'] = 10;
    $val = $p['y'];
    $item = ['Display Name' => "", 'id' => 0];
    $item['Display Name'] = "Hello";
}
